### ISSUE TITLE
Create wascc demo in C or C++

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#101]
This example should have the code we use to compile the module and a pod spec that loads user specified env vars, and env vars from the downward API/config maps/secrets. These env vars should be printed out via an http request to the pod

**Comment by bacongobbler** [comment]
Removing "good first issue" as this involves writing a waSCC actor SDK in C/C++ as one currently does not exist.

https://github.com/wascc/wascc-actor

**Comment by autodidaddict** [comment]
waSCC will soon support Tinygo, AssemblyScript, Zig, and we already support Rust. There are no plans to write a C or C++ Actor SDK.

**Comment by thomastaylor312** [comment]
Closing per @autodidaddict's feedback
