### ISSUE TITLE
Create a team cargo account

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#107]
For the github action, we're currently using a personal token to release krustlet to crates.io. We should create a team account and use that instead.

**Comment by thomastaylor312** [comment]
This can be done with `cargo owner --add github:deislabs:<teamname>` once we publish the 0.2 crate

**Comment by thomastaylor312** [comment]
Oh, if we want to use a bot for it (instead of someone's credentials), we'd need to create a GH bot that we can log in to crates with and add to the team

**Comment by thomastaylor312** [comment]
Added the krustlet-maintainers group as an owner. We can add a bot down the line
