### ISSUE TITLE
Remove panic from wasi stop

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#129]
Although we cannot actually stop a running wasi runtime, we can drop the handle from the map and _not_ panic so we don't stop the whole thing from running

**Comment by bacongobbler** [comment]
Hey @thomastaylor312, can you please share a little more detail on how this can occur and how others can reproduce this? I'm assuming this has to do with a `kubectl delete pod`?

**Comment by thomastaylor312** [comment]
Right now when we call `stop` on a wasi runtime, it panics because of the `unimplemented` macro. This will happen any time a pod is deleted
