### ISSUE TITLE
prompt for --pfx-password

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#140]
Most CLI tools do not allow users to enter the password on the command line. We should instead open a prompt window to ask for the password.

**Comment by thomastaylor312** [comment]
So would we leave the environment variable option for users? Also, should we have a `--pfx-password-stdin` option?

**Comment by bacongobbler** [comment]
> Also, should we have a --pfx-password-stdin option?

Yeah, I think this is the best route. Either that, or make `--pfx-password` a boolean flag that opens the prompt window.

You have to be very careful how you pass passwords to command lines. You'll end up leaving it open to sniffing using tools like `ps`, looking it up in /proc/1/cmdline, or in history files like ~/.bash_history.

> So would we leave the environment variable option for users?

In general, best practices dictate either allowing users to pass in a config filepath (like a git-config) or prompting for the password on stdin. An environment variable leaves that vulnerability open too as malicious users can sniff it under /proc/1/environ.

**Comment by thomastaylor312** [comment]
I did want to enhance the config module to support a config file as well, so we can probably do it there

**Comment by bacongobbler** [comment]
closing in favour of #141 and #202
