### ISSUE TITLE
docs(intro): What is Krustlet?

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#156]
While writing the announcement post, I noticed in the documentation that we don't have a section that explains Krustlet. The README goes into a little detail, but it'd be great to have a section in the introductory material that answers the question "what is Krustlet, and how is it relevant to my interests?"

**Comment by k82cn** [comment]
hm... and "how this project keep compatibillity with k8s/upstream?"

**Comment by bacongobbler** [comment]
In what way?

**Comment by k82cn** [comment]
> In what way?

In anyway :) So we will not keep compatibillity ?

**Comment by bacongobbler** [comment]
I'm still not fully sure what you're trying to get at here, @k82cn.
