### ISSUE TITLE
Add more status and phase updates

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#157]
Status updates should reflect if a module is being pulled (e.g. `ContainerCreating`) and should also move to `Completed` phase properly (right now the output shows `ExitCode:0`)

**Comment by itowlson** [comment]
@thomastaylor312 Is this bound up with the status refactor or can it be progressed separately?  It feels like we will need to make container states and transitions at least a bit more explicit in order to tackle this effectively...

**Comment by thomastaylor312** [comment]
Yeah, this is basically tied together with the status (and possible state machine) refactor for now, as any effort to implement this will either be undone or make the refactor harder

**Comment by kflansburg** [comment]
@thomastaylor312 What else are we thinking here? Can this be closed?

**Comment by thomastaylor312** [comment]
Yeah at this point this can be closed
