### ISSUE TITLE
k3d: cannot retrieve logs

### ISSUE THREAD

**Issue by deitch** [deislabs/krustlet#168]
This is a very interesting project; congratulations! Given how much interesting work comes out of deislabs with OCI (I use oras happily), I should not be surprised.

I run through the getting started demo - run a k3d cluster, run krustlet-wasi, it registers as a node, and launched the `hello-world-wasi-assemblyscript` example. It runs and exits with `0`, which makes sense. But I cannot get the logs:

```
$ kubectl logs hello-world-wasi-assemblyscript
Error from server: Get https://MacBook-Pro-6.localdomain:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: failed to find Session for client MacBook-Pro-6.localdomain
```

I found it odd that it tries to get to https://MacBook-Pro-6.localdomain:3000/, when I explicitly told it to go to `Krustlet`:

```
/usr/local/bin/krustlet-wasi --node-ip 192.168.99.59 --pfx-password password --node-name krustlet
```

**Comment by thomastaylor312** [comment]
@deitch You'll need to set `--hostname` as well in this case. Technically the node name in kubernetes can be different from the hostname, so that is why we have two flags. Let me know if that works for you!

**Comment by bacongobbler** [comment]
I sense an opportunity to improve the documentation with regards to `--node-name` and `--hostname` :)

**Comment by deitch** [comment]
Yeah, definitely improving docs. I got it a step forward - I set the hostname to the IP - but still get logs errors. On the other hand, I _can_ curl it manually:

```
$ kubectl logs hello-world-wasi-assemblyscript
Error from server: Get https://192.168.99.59:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: failed to find Session for client 192.168.99.59
```

So I tried it manually:

```
curl -k -i https://192.168.99.59:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript
HTTP/1.1 200 OK
content-length: 124
date: Thu, 09 Apr 2020 17:47:17 GMT

hello from stdout!
hello from stderr!
CONFIG_MAP_VAL=cool stuff
POD_NAME=hello-world-wasi-assemblyscript
FOO=bar
Args are:
```

And on krustlet's output:

```
krustlet-wasi --node-ip 192.168.99.59 --node-name krustlet --hostname 192.168.99.59 --pfx-password password
[2020-04-09T17:46:13Z ERROR kubelet::server] error handling connection: server closed session with no notification
[2020-04-09T17:46:21Z ERROR kubelet::server] error handling connection: server closed session with no notification
[2020-04-09T17:46:46Z ERROR kubelet::server] error handling connection: server closed session with no notification
[2020-04-09T17:47:02Z ERROR kubelet::server] error handling connection: unknown Cert Authority
[2020-04-09T17:47:05Z ERROR kubelet::server] error handling connection: unknown Cert Authority
```

**Comment by bacongobbler** [comment]
I see you mentioned following the "getting started" demo... I'm interested in which [how-to guide](https://github.com/deislabs/krustlet/blob/master/docs/howto/README.md) you followed to set up Krustlet. Can you give us a link to the setup guide you used as reference material?

That way we can try to replicate the issue locally.

**Comment by deitch** [comment]
Sure. 

1. Started with the [main page](https://github.com/deislabs/krustlet)
1. Jumped to the introduction towards the bottom, which took me [here](https://github.com/deislabs/krustlet/blob/master/docs/intro/README.md)
1. Installed krustlet based on [here](https://github.com/deislabs/krustlet/blob/master/docs/intro/install.md) - I just downloaded the macOS binary from the releases page on github
1. Jumped to the [quick start](https://github.com/deislabs/krustlet/blob/master/docs/intro/quickstart.md) page
1. Started k3d to use as my cluster (Step 1)
1. Started krustlet for local, based on the link in Step 2, which [took me here](https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-on-kind.md) to find the IP, set up the certs, etc. with the modifications suggested above in this issue
1. Ran `kubectl get no` to be sure I saw it
1. Picked an example and ran the yaml, specifically [this](https://github.com/deislabs/krustlet/blob/master/demos/wasi/hello-world-assemblyscript/k8s.yaml)
1. `kubectl get pod` to see that it had completed
1. `kubectl logs hello-world-wasi-assemblyscript` to get the error

**Comment by bacongobbler** [comment]
Hi there! Jumping back on this issue. Did you manage to figure out your issue? If so can we close this?

**Comment by deitch** [comment]
Hi @bacongobbler ; I haven't looked at it in a while. I will try to recreate now.

**Comment by deitch** [comment]
Some improvement. 

* I need to set the `--hostname <ip>` to the explicit IP or a resolvable hostname of my local host 
* when I do, I get a cert problem: 

```
Error from server: Get https://192.168.99.59:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: x509: cannot validate certificate for 192.168.99.59 because it doesn't contain any IP SANs
```

Indeed, the example [here](https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-on-kind.md) only includes a CN, not any SANs. That may be because adding SANs with openssl is a pain in the neck. I actually have my own local utility in go that I use for generating certs. I used to use cfssl, now I have my own [here](https://github.com/deitch/ssl-utils). I never had it generate just a key and CSR; maybe I will add it.

In any case, the docs need a bit of help, it looks like.

**Comment by bacongobbler** [comment]
TLS bootstrapping was just merged in #275, so a lot of the setup steps you ran into earlier should be vastly simplified. We still have to document the new setup process, but once that's done it should be much easier as Krustlet will self-generate a TLS certificate. All you'll have to do is approve the certificate sign request from Kubernetes.

```
$ just run-wasi
```

And from another terminal:

```
$ kubectl certificate approve ULTRALISK-tls
$ kubectl get nodes
NAME                 STATUS   ROLES    AGE     VERSION
kind-control-plane   Ready    master   9m49s   v1.18.2
krustlet-wasi        Ready    agent    8m6s    0.2.1
```

> * I need to set the `--hostname <ip>` to the explicit IP or a resolvable hostname of my local host

I'm curious why you need to set this up though. It's unnecessary for me. A call to `just run-wasi` will automatically find and use the correct hostname (ULTRALISK). Setting the hostname to an IP address should not be necessary.

Can you share more information why you needed to do this? Perhaps there's some piece missing here that we either need to document or fix up. Thanks!

**Comment by bacongobbler** [comment]
v0.3.0 with TLS bootstrap support was released yesterday if you want to give it a try again and want to provide feedback.

**Comment by deitch** [comment]
I gave it a shot. I started up a k3d cluster, then followed the bootstrapping [here](https://github.com/deislabs/krustlet/blob/master/docs/howto/bootstrapping.md).

Interestingly, there were no outstanding csrs, and the node showed as ready:

```
$ kubectl get csr --all-namespaces
No resources found
$ kubectl get no
NAME                     STATUS   ROLES    AGE     VERSION
k3d-k3s-default-server   Ready    master   9m53s   v1.17.4+k3s1
macbook-pro-10.local     Ready    agent    85s     0.3.0
```

I notice that it still is called `macbook-pro-10.local`. 

Although there is nothing on stdout/stderr from running `krustlet-wasi` (I also couldn't find a `--debug` or `--v=<int>` option).

```
$ krustlet-wasi --port 3000 --bootstrap-file $HOME/.krustlet/config/bootstrap.conf

```

I applied the example anyways, got:

```
$ kubectl apply -f hello-world-assemblyscript/k3s.yaml
configmap/hello-world-wasi-assemblyscript created
pod/hello-world-wasi-assemblyscript created
$ kubectl get po
NAME                              READY   STATUS       RESTARTS   AGE
hello-world-wasi-assemblyscript   0/1     ExitCode:0   0          5s
$ kubectl logs hello-world-wasi-assemblyscript
Error from server: Get https://MacBook-Pro-10.local:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: local error: tls: bad record MAC
```

I tried again with `--hostname <ip>`, same process, I get a different error:

```
$ kubectl apply -f ~/.krustlet/example/hello-world-assemblyscript/k3s.yaml
configmap/hello-world-wasi-assemblyscript created
pod/hello-world-wasi-assemblyscript created
$ kubectl get pod
NAME                              READY   STATUS       RESTARTS   AGE
hello-world-wasi-assemblyscript   0/1     ExitCode:0   0          4s
$ kubectl logs hello-world-wasi-assemblyscript
Error from server: Get https://192.168.99.59:3000/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: x509: cannot validate certificate for 192.168.99.59 because it doesn't contain any IP SANs
```

I guess that is something.

**Comment by thomastaylor312** [comment]
That is an interesting bug. Basically, when the cert was provisioned it didn't end up with an IP SAN, which it should have. Was this just with a bare k3d cluster running locally? Let me know and then I'll try to replicate the problem on my machine

**Comment by deitch** [comment]
> when the cert was provisioned it didn't end up with an IP SAN, which it should have

I find it interesting that I didn't even see the CSR, but it must exist? 🤷‍♂️

> Was this just with a bare k3d cluster running locally?

As simple as it gets:

```
$ k3d c
$ export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
$ # do krustlet stuff
```

**Comment by bacongobbler** [comment]
Weird. I think I found the issue.

It's because most Kubernetes distributions ignore the hostname when trying to initiate a connection to the node. k3d uses the hostname to make requests.

```
><> k logs hello-world-wasi-assemblyscript
Error from server: Get https://ULTRALISK:3001/containerLogs/default/hello-world-wasi-assemblyscript/hello-world-wasi-assemblyscript: failed to find Session for client ULTRALISK
```

In comparison, if I use `kind` with the exact same setup parameters:

```
><> k get po
NAME                              READY   STATUS       RESTARTS   AGE
hello-world-wasi-assemblyscript   0/1     ExitCode:0   0          1s
><> k logs hello-world-wasi-assemblyscript
hello from stdout!
hello from stderr!
POD_NAME=hello-world-wasi-assemblyscript
FOO=bar
CONFIG_MAP_VAL=cool stuff
Args are:
```

I think we simply need to make the suggestion to not use k3d until we can figure out a resolution. @deitch please use an alternative like `kind` or `minikube` for local development.

Thanks for the bug report!

**Comment by deitch** [comment]
> because most Kubernetes distributions ignore the hostname when trying to initiate a connection to the node. k3d uses the hostname to make requests.

What do the others do? It has to use _something_. Is it the IP?

**Comment by bacongobbler** [comment]
Yes.

**Comment by jiayihu** [comment]
Not sure if it helps anyone but I had the same issue. I was trying to run krustlet on my MBP with a k3s cluster on raspberry. To get the logs I just had to run as `krustlet-wasi --node-ip 192.168.1.126 --hostname 192.168.1.126`, probably because otherwise the k3s server can't resolve the hostname since my laptop it's not in the cluster DNS config

**Comment by turbosree** [comment]
I got the same issue in minikube. 

$ kubectl logs hello-world-wasi-c
Error from server: Get "https://192.168.49.2:3001/containerLogs/default/hello-world-wasi-c/hello-world-wasi-c": dial tcp 192.168.49.2:3001: connect: connection refused

$ curl -k -i https://192.168.49.2:3001/containerLogs/default/hello-world-wasi-c/hello-world-wasi-c
curl: (7) Failed to connect to 192.168.49.2 port 3001: Connection refused

krustlet-wasi running successfully with command: just run-wasi

$ minikube version
minikube version: v1.21.0
commit: 76d74191d82c47883dc7e1319ef7cebd3e00ee11
