### ISSUE TITLE
Feature request: add --node-labels command line option

### ISSUE THREAD

**Issue by peterhuene** [deislabs/krustlet#184]
Kubelet's `--node-labels` option is used by tools such as [eksctl](https://eksctl.io/) to manage groups of nodes in a K8S cluster.

Here's the help text for the option:

```
Labels to add when registering the node in the cluster.
Labels must be key=value pairs separated by ','.
Labels in the 'kubernetes.io' namespace must begin with an allowed prefix
(kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set
(beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os,
failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone,
failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone,
kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type,
kubernetes.io/os)
```

It would be nice if krustlet also supported this option so that external node management with such tools would also work.

**Comment by thomastaylor312** [comment]
Labeling this as a good first issue if anyone wanted to get started with krustlet. Shouldn't be too hard to add on to things and the hardest part will likely just be the parsing/validation for the CLI flag (the `Config` object can just accept a `HashMap`)

**Comment by DerekStrickland** [comment]
I've forked and branched.  Trying to figure out how to test it now.  Hopefully, I'll have something for you today or tomorrow.
