### ISSUE TITLE
Panic on EKS while watching nodes (401 unauthorized)

### ISSUE THREAD

**Issue by peterhuene** [deislabs/krustlet#187]
I don't have repro steps other than standing up an [EKS cluster](https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-on-eks.md) and waiting for the node to show up as `NotReady`.  Prior to the panic, the node was `Ready` and was successfully running WebAssembly applications.

I pulled this from the service log on one of the `krustlet` nodes:

```
Apr 15 00:38:56 ip-192-168-71-217.us-west-2.compute.internal krustlet[2260]: [2020-04-15T00:38:56Z WARN  kube::runtime::informer] Unexpected watch error: Api(ErrorResponse { status: "Failure", message: "Unauthorized", reason: "Unauthorized", code: 401 })
Apr 15 00:38:56 ip-192-168-71-217.us-west-2.compute.internal krustlet[2260]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Api(ErrorResponse { status: "Failure", message: "Unauthorized", reason: "Unauthorized", code: 401 })', /home/ec2-user/.cargo/git/checkouts/krustlet-dd9f49a0b51f9977/31f4940/crates/kubelet/src/kubelet.rs:78:41
```

which points at [this unwrap call](https://github.com/deislabs/krustlet/blob/master/crates/kubelet/src/kubelet.rs#L78) during polling for pods.

I don't know why the EKS managed API server is occasionally returning a 401 yet, but I thought I'd file an issue here in case anyone else runs into this.

Unfortunately, after the panic, the `krustlet` service goes into a failure loop when attempting to reclaim the existing node registration (possibly related to [this issue](https://github.com/deislabs/krustlet/issues/150)?):

```
Apr 15 00:51:32 ip-192-168-71-217.us-west-2.compute.internal krustlet[4144]: thread 'main' panicked at 'Unable to recreate node...aborting: Api(ErrorResponse { status: "Failure", message: "nodes \"ip-192-168-71-217.us-west-2.compute.internal\" is forbidden: User \"system:node:ip-192-168-71-217.us-west-2.compute.internal\" cannot delete resource \"nodes\" in API group \"\" at the cluster scope", reason: "Forbidden", code: 403 })', /home/ec2-user/.cargo/git/checkouts/krustlet-dd9f49a0b51f9977/31f4940/crates/kubelet/src/node.rs:47:21
```

**Comment by peterhuene** [comment]
If I had to hazard a guess as to what's going on with the 401 is that the IAM auth token that was retrieved via an `exec` action in the `kubeconfig` expired and needs to be renewed.

We should probably handle auth failures in polling such that auth tokens can be renewed.

**Comment by peterhuene** [comment]
The `exec` action only once when creating a `kube::config::Config`, so we would need to have some sort of "config provider" to the `Kubelet` so it can request another kubeconfig upon a failure to poll due to an authorization failure.

**Comment by peterhuene** [comment]
The IAM auth tokens appear to be for 15 minutes, which about corresponds to the time I see the krustlet node stay up, so I think that's the likely cause.

In the `Kubelet` implementation (and other places where an API client is used), we'll need to handle auth failures gracefully by retrying with a new configuration at least one time.

**Comment by peterhuene** [comment]
Unfortunately `kube::config::Configuration` is the end result of running the exec action and the expiration time of the token is internally de-serialized, but unused.

Unless the `kube` crate changes this abstraction, there's no way, as far as I can tell, to check if the token expires *before* sending a request and responding to a 401 😞 .

**Comment by rylev** [comment]
So I looked into this. [Here](https://github.com/clux/kube-rs/blob/3d9b9411e2c9e39adee066a8c6b7a96acecdee09/kube/src/config/mod.rs#L140-L145) is where the exec is happening and where `token` is being taken from `ExecCredentialStatus` but `expiration_timestamp` is ignored.  The token is then just [stuffed into the headers](https://github.com/clux/kube-rs/blob/3d9b9411e2c9e39adee066a8c6b7a96acecdee09/kube/src/config/mod.rs#L184).

I will open an issue up on Kube for being able to reauthenticate.

**Comment by thomastaylor312** [comment]
@rylev So is this purely an upstream issue or is there something we could do to mitigate in the meantime? I am inclined to wait on upstream as the kube-rs maintainer is super responsive

**Comment by rylev** [comment]
I believe we could mitigate this ourselves by responding to 401s by building a new client with `kube::Client::try_default`. I'm not sure how easy the fix will be in upstream as there's not a clear way that `kube` should handle this issue.

**Comment by thomastaylor312** [comment]
So I ended up giving it a shot by fixing it in the upstream library. I'll open a PR once I get a chance to test this

**Comment by thomastaylor312** [comment]
@jingweno and @peterhuene can one (or both of you) try building krustlet, replacing the `kube` dependency with https://github.com/thomastaylor312/kube-rs/tree/feat/token_refresh and let me know if it works?

**Comment by bacongobbler** [comment]
Okay, I did a deep dive on client-go's architecture with client refresh tokens. I [wrote up my findings](https://github.com/clux/kube-rs/issues/224#issuecomment-618604682) upstream, and it looks like your implementation aligns with that model. I'll go give it a spin and take a closer look at the code, but your approach looks sane to me.

**Comment by peterhuene** [comment]
@thomastaylor312 your fix is looking solid so far.  I'll leave the nodes running for a little while and let you know if things change.

**Comment by peterhuene** [comment]
The krustlet nodes have been up for at least an hour without panicking from auth expiration 👍

**Comment by thomastaylor312** [comment]
Sweet. I'll tidy up my code and push a PR up to `kube`

**Comment by thomastaylor312** [comment]
https://github.com/clux/kube-rs/pull/234

**Comment by jingweno** [comment]
Late to the party (I wish I could work on this fulltime 😄 ). I pulled in the fix from https://github.com/deislabs/krustlet/compare/master...jingweno:token_refresh_test, burned an AMI image, and created a new cluster. Everything looks good so far. I will also leave it running and report back the status next week.

**Comment by jingweno** [comment]
The nodes have been up for 2d and appear to be healthy. So I think we can declare the fix works!

```
k get node
NAME                                           STATUS   ROLES   AGE   VERSION
ip-192-168-13-165.us-west-2.compute.internal   Ready    agent   2d    v1.17.0
ip-192-168-52-161.us-west-2.compute.internal   Ready    agent   2d    v1.17.0
```

**Comment by thomastaylor312** [comment]
@jingweno Great! The PR should be merged upstream very soon and then I can pull in the changes to Krustlet
