### ISSUE TITLE
Update demos to use volumes

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#196]
Update all of our current demos to use volumes. This task should be done right before we release 0.2 so we don't confuse any current users of 0.1

**Comment by thomastaylor312** [comment]
Labeling this as a good first issue. If you'd like to get your feet wet with basic wasm module compilation, this would give you the chance to update the code to read from volumes and print it to logs

**Comment by bacongobbler** [comment]
#222 introduced a volume-based demo for the waSCC runtime. I'd love to see a wasmtime demo! Most of the code (asides the actor) could be re-used as the hostPath and mountPaths are the same for the WASI provider.

**Comment by bacongobbler** [comment]
Working on a WASI demo.
