### ISSUE TITLE
Create configurable testing module for e2e tests

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#205]
We need a module that we can configure to read and write from specific directories and to output anything else needed for our e2e tests. 

One outstanding question is whether we should put it in this repo or have it be a separate thing

**Comment by bacongobbler** [comment]
If it makes sense as its own standalone repository, then perhaps it should be broken out of kruslet. On that same note though, have we done any research on other crates out there that may already provide this functionality for us?

For example: https://github.com/mindsbackyard/galvanic-test

**Comment by itowlson** [comment]
I'll take a crack at this as it would be useful for the init containers work.
