### ISSUE TITLE
Create automatic cleanup for tests

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#206]
Right now if a test fails, cleanup of testing resources does not happen. We should either implement a "Guard" style resource that wraps the k8s resource with a `Drop` implementation or using a crate that allows for cleanup steps to be run

**Comment by thomastaylor312** [comment]
Please note that I tried this with the Guard style resource and because there is no `async Drop`, you'll need to spin things off on a thread with `thread::spawn` if you go that route. Just trying to block on the future causes it to freeze up

**Comment by itowlson** [comment]
It looks like you can't use `catch_unwind` either because the `kube::Client` type isn't unwind safe.

**Comment by itowlson** [comment]
And, more fundamentally, because async closures are not yet in stable Rust.  So even if you make the cleanup code completely self-contained, you can't pass it to `catch_unwind` (or `set_hook`) because the compiler requires you to handle the future but you can't `await` on it.

**Comment by thomastaylor312** [comment]
@itowlson Did you give implementing `Drop` a try?

**Comment by itowlson** [comment]
@thomastaylor312 Yes - the trouble I had with `Drop` was getting the spawned thread to run an async function because of the _drum roll_ 'async lambdas are not stable' issue.

**Comment by rylev** [comment]
@itowlson have you tried creating a runtime and running the async task?

```rust
let mut rt = Runtime::new()?;


```

**Comment by itowlson** [comment]
@rylev YAY!  Combined your suggestion with one of @thomastaylor312's and we have ignition!
