### ISSUE TITLE
Making things Async

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#21]
Bringing up the discussion question of: Should we make kubelet and all providers async? This would involve using tokio as it is the underlying runtime for wasmtime as well.

**Comment by rylev** [comment]
I am unsure whether we would benefit from the added complexity of making things async. It does make some sense in certain parts of the code. For instance, if we don't make things async we would need to maintain our own thread pool for pulling all the wasm binaries in a given pod (as specified in #24). 

However, #25 can easily be modeled as blocking calls on a worker thread. Given that we don't have to field requests from K8s in a large volume, it may be simpler to just use a thread pool to handle this.

**Comment by thomastaylor312** [comment]
I like that idea. Is tokio the best choice for that here?

**Comment by rylev** [comment]
Given that we will already need a runtime for `kube`, we should just stick to using tokio and not use a custom thread pool.

**Comment by thomastaylor312** [comment]
@rylev was there other work besides #40 that needs doing before we close this?

**Comment by rylev** [comment]
@thomastaylor312 we should do another pass over the code to make sure we're not blocking anywhere. We can either keep this opened until that's done or create another issue that's more specific.
