### ISSUE TITLE
Add stopping of long running WASM processes

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#212]
Now that wasmtime has [support for stopping a running instance](https://github.com/bytecodealliance/wasmtime/pull/1490), we should be able to add this in to our `Stop` implementation for the wasi provider.

This will need to wait until a new version of the wasmtime crate is released

**Comment by peterhuene** [comment]
@thomastaylor312 0.16.0 of wasmtime has been released and should contain the interruption feature.

**Comment by thomastaylor312** [comment]
Awesome. Thanks for letting us know
