### ISSUE TITLE
Add handling for modify events where the image changes

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#214]
For 0.2 we are only handling modify events where the pod is marked for termination. We need to implement functionality for stopping the old "container" and starting a new one when `spec.containers[*].image` or `spec.initContainers[*].image` change

**Comment by Haegi** [comment]
Is there a recommended way to find out whether the image has changed or not.
Unfortunately, `.image` holds the new image immediately after the modification. That makes it hard to find out whether the image has changed. 
Would it be a good solution to introduce a new pod field, which holds the current images running in the pod?

**Comment by thomastaylor312** [comment]
Yeah, I wasn't sure on the best way to do this. `client-go` on the update method passes the old and the new object, but the `kube` crate doesn't. I think the ideal option is to add support for that to the `kube` crate, but that isn't a requirement for this feature.

I think we should probably just keep an in-memory map of any pods and their current images for now. A stretch goal would be to only keep track of bare pods (as other pods created from controllers just delete the pods and create new ones)

**Comment by bacongobbler** [comment]
I believe this has now been implemented with the state machine refactor. Changing the container image triggers a re-pull with the new image.
