### ISSUE TITLE
microk8s works w/ Krustlet

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#227]
Krustlet appears to work well with [microk8s](https://microk8s.io).

An advantage of microk8s is that it's easily-installed on a single workstation and Krustlet may run alongside it.

```bash
microk8s.kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
microk8s   Ready    <none>   13m   v1.18.2-41+b5cdb79a4060a3
krustlet   Ready    agent    48s   v1.17.0
```

> **NB** Using `microk8s.kubectl` to prove the point; `kubectl` may be used directly too

And:

```
KUBECONFIG=/var/snap/microk8s/current/credentials/client.config \
./krustlet-wasi \
--node-ip=127.0.0.1 \
--node-name="krustlet" \
--pfx-password="password" \
--pfx-path=./krustlet.pfx
```

> **NB** Using `/var/snap/microk8s...` to prove the point

And, e.g:

```
microk8s.kubectl apply --filename=.../demos/wasi/hello-world-rust/k8s.yaml
configmap/hello-world-wasi-rust created
pod/hello-world-wasi-rust created

microk8s.kubectl get pods
NAME                    READY   STATUS       RESTARTS   AGE
hello-world-wasi-rust   0/1     ExitCode:0   0          8s

microk8s.kubectl logs pod/hello-world-wasi-rust
hello from stdout!
hello from stderr!
FOO=bar
POD_NAME=hello-world-wasi-rust
CONFIG_MAP_VAL=cool stuff
Args are: []
```

I forked the repo to document this but the documentation is very repetitive (and thus potentially difficult for everyone to maintain) and would -- IMO -- benefit from refactoring into... assuming you have a cluster... create service account, certificates etc., 

Thoughts?

**Comment by bacongobbler** [comment]
It's okay if the HOWTO guides are a little repetitive, as they are intended to be self-sufficient. The [Quickstart guide](https://github.com/deislabs/krustlet/blob/master/docs/intro/quickstart.md) shows the high-level "here's how to set up Krustlet", along with a link to each HOWTO depending on what provider is being used.

If you want to create a generic HOWTO guide, we'd welcome that, though the [Krustlet with Inlets](https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-with-inlets.md) guide was also intended to demonstrate how to set up Krustlet with a generic cluster.

Let us know how you'd like to proceed.

**Comment by DazWilkin** [comment]
OK... 

On the basis that someone may benefit from a microk8s document, I'll complete it and submit the PR.

Thanks for the interesting project and the quick reply.
