### ISSUE TITLE
Interest for Krustlet w/ GKE?

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#236]
As a former Googler, proponent of Google Cloud and fan of [GKE](https://cloud.google.com/kubernetes-engine), I'd like to see documentation for Krustlet/GKE, but... $$$

If you're seeing interest to justify this, I'll suck it up on my dime.

**Comment by bacongobbler** [comment]
We would love to see documentation on GKE!

**Comment by DazWilkin** [comment]
I'm somewhat distracted today, I have most of the GKE stuff documented but must resolve a routing issue. When I resolve it, I'll submit a PR.

**Comment by DazWilkin** [comment]
The routing issue may be a red-herring and appears to have surfaced original with virtual kubelet:

https://github.com/virtual-kubelet/virtual-kubelet/issues/122

If that is a red-herring, then that leaves #238 

Will resume tomorrow.

Documentation's mostly done (just doesn't yet result in a working `hello-world-wasi-rust`)

**Comment by DazWilkin** [comment]
@thomastaylor312  @bacongobbler -- unimportant but, if you ideas, I'd be grateful...

The routing issue was user error (the VM must be named `krustlet` for the routing ;-)).

However, I'm now receiving:

```bash
kubectl logs pod/hello-world-wasi-rust
Error from server: Get https://10.138.0.4:3000/containerLogs/default/hello-world-wasi-rust/hello-world-wasi-rust: x509: cannot validate certificate for 10.138.0.4 because it doesn't contain any IP SANs
```

The private IP of the `krustlet` VM is `10.138.0.4`:

```bash
INSTANCE="krustlet" # Match CN
gcloud compute instances describe ${INSTANCE} \
--project=${PROJECT} \
--zone=${ZONE} \
--format="value(networkInterfaces[0].networkIP)"
10.138.0.4
```
Logging from `krustlet-wasi` reports:
```bash
RUST_LOG=info \
KUBECONFIG=${PWD}/kubeconfig-sa \
./krustlet-wasi \
--node-ip=10.138.0.4 \
--node-name=krustlet \
--pfx-password=password \
--pfx-path=./krustlet.pfx
```
But:
```
[2020-05-07T18:13:58Z ERROR kubelet::server] Error handling server connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1544:SSL alert number 42
```

A pod running on the regular node can resolve `krustlet`:
```bash
kubectl exec --stdin --tty dnsutils -- nslookup krustlet
Server:		10.39.240.10
Address:	10.39.240.10#53

Non-authoritative answer:
Name:	krustlet.us-west1-a.c.dazwilkin-200507-krustlet.internal
Address: 10.138.0.4
```

Any ideas?

**Comment by kflansburg** [comment]
It looks like you are querying the Krustlet API by IP instead of `krustlet`. I'm not sure what causes you to do that, but you could either try to switch to using the domain name, or you could regenerate your Krustlet's TLS Cert with subjectAltName equal to the private IP (10.138.0.4). It doesn't look like this is easily done from the command line with `openssl`. 

https://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-the-command-line

**Comment by kflansburg** [comment]
The bootstrap script for EKS appears to set the subjectAltName:

https://github.com/deislabs/krustlet/blob/master/docs/howto/assets/eks/files/bootstrap.sh

**Comment by DazWilkin** [comment]
@kflansburg thanks for the reply.

I took the happy (easy) path through the config but, evidently, it doesn't work :-(

I don't understand how the name|IP resolution works with the Krustlet so that makes it more challenging for me. For instances in the same zone, the instance name (e.g. `krustlet`) will resolve automatically to the VM's IP but this generates the same error. For cross-zone traffic, I would need to include the zone in the instance's DNS for correct resolution.

I'll have a look at the EKS approach, thank you.

**Comment by kflansburg** [comment]
I believe that when the krustlet registers, the cluster DNS (CoreDNS or whatever) will point the node name to the node IP, I'm not sure if `kube-api-server` queries by hostname or IP, but I think its pretty common to set the subjectAltName with he node's public and private IPs if you haven't done that already. As far as cross zone traffic, are these zones in the same network? There may be routing issues rather than DNS issues at play there.

**Comment by squillace** [comment]
Don't give up, @DazWilkin!!! We'd love to have docs for this on GKE; if it can't run on k8s everywhere, it's a failing. :-)

**Comment by DazWilkin** [comment]
@squillace thanks for the support! I am planning to return to this today.

I will follow @kflansburg guidance and determine whether the DNS naming is the issue.

I want to ensure my documentation reflects both regional and zonal clusters.

The documentation is written and will be mostly unchanged, I need just get it working ;-)

**Comment by thomastaylor312** [comment]
@DazWilkin Also, you may want to make sure you have both `--node-name` and `--hostname` set. The first flag is the name of the object in kubernetes. The second is the hostname of the node that k8s should use to contact the Kubelet API

**Comment by DazWilkin** [comment]
Success!

```
kubectl logs pods/hello-world-wasi-rust
hello from stdout!
hello from stderr!
CONFIG_MAP_VAL=cool stuff
FOO=bar
POD_NAME=hello-world-wasi-rust
Args are: []
```

The issue appears to be with the `subjectAltNames` of the CSR.

**Comment by thomastaylor312** [comment]
Yeah, SANs are a bit funky. I have an example one locally, but it might be good to add an example to the repo as part of the documentation for this
