### ISSUE TITLE
Feature: templated WASM/I developer experience with GH action for build/push

### ISSUE THREAD

**Issue by squillace** [deislabs/krustlet#241]
WASM right now has relatively limited feature range using WASI as a compilation target. In addition, Krustlet feature support is evolving as we speak. Our initial experience, despite all this, is strong, providing good motivation for moving forward. 

However, as we do so we are asking each developer to understand how to build their own WASI modules at some point we should create something very straightforward in at least Rust and TS/JS to 
- create a helloworld service in wasi that contains a GH action necessary to build and push the wasm to a registry (so that when pushed it just works from the dev iteration)
- Sets up VS Code to get basic developer functionality working for the two items

This is very much a post .2 or .3 workflow. :-)

**Comment by bacongobbler** [comment]
How would this be solved in the krustlet project? Should this be something which is handled by another project? Sounds to me like a job for [yeoman](https://yeoman.io/) or something similar. We have demo apps available.

Putting it another way: is it the role and responsibility of the Kubelet project to demonstrate how to create a helloworld docker container, or is that the role and responsibility of a developer tool ecosystem?

**Comment by radu-matei** [comment]
Generators like Yeoman sound like a good fit for this - additionally, I would also suggest we look at VS Code dev containers before thinking about extensions.

**Comment by squillace** [comment]
these are all good suggestions. in reality, though GH has us assume our "projects" are scoped to a repository, they never are -- so @bacongobbler you're right that this is not scoped to krustlet. I'm happy to create a new project somewhere for this, but if we do not have it, krustlet will be less successful. 

Yeoman and/or VS code and/or remote containers are all great ideas; though I dislike the idea of a good dev env/ux depending on a specific account. yet the functionality is so perfect.....

**Comment by itowlson** [comment]
I'm having a crack at a Yeoman-based approach at https://github.com/deislabs/generator-wasm-oci-rust - feedback welcome.

**Comment by itowlson** [comment]
Generator/template moved to https://github.com/deislabs/generator-wasm-oci

**Comment by bacongobbler** [comment]
thanks @itowlson! I'm going to close this as there's no action to be taken here on Krustlet's side. We can point users to projects like the yeoman generator @itowlson wrote to handle this use case.

Thanks for the suggestion @squillace!
