### ISSUE TITLE
Implement service support 

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#245]
I'm able to run the WASI demos (greet, hello) without issue. Both of these demos have READMEs that explain what to expect.

I'm able to run (seemingly) both the WASCC demos (greet, uppercase) **but** there's no explanation as to how to confirm that these are running successfully and I'm unclear that they are.

It **may** be that my configuration is not working correct for WASCC but I'm unable to confirm this because I'm unable to explore these demos fully.

Both Pods appear to run HTTP endpoints on `:8080`.

Absent the ability to `kubectl port-forward` to these pods, I've tried exposing them as services. But the service(s) don't receive endpoints and appear unable to select the WASCC pods.

I'm evidently misunderstanding and|or doing something incorrectly but the demos don't explain what I should expect or do next.

```
kubectl get pods
NAME                                    READY   STATUS       RESTARTS   AGE
greet                                   1/1     Running      0          10m
uppercase                               1/1     Running      0          10m
```
Describing `greet` appears to show everything running as expected (8080/8080):
```
kubectl describe pod/greet
Name:         greet
Namespace:    kube-system
Priority:     0
Node:         krustlet/
Labels:       app=greet
Annotations:  Status:  Running
IP:           
IPs:          <none>
Containers:
  greet:
    Container ID:   
    Image:          webassembly.azurecr.io/greet-wascc:v0.4
    Image ID:       
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 12 May 2020 09:31:32 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      PORT:  8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7956z (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  default-token-7956z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7956z
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/arch=wasm32-wascc
                 beta.kubernetes.io/os=linux
                 kubernetes.io/role=agent
Tolerations:     krustlet/arch=wasm32-wascc:NoExecute
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned kube-system/greet to krustlet
```
Exposing both WASCC pods as services (`--port=8080 --target-port=8080`):
```
kubectl get services
NAME        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
greet       ClusterIP   10.152.183.63    <none>        8080/TCP                 10m
uppercase   ClusterIP   10.152.183.94    <none>        8080/TCP                 10m
```
But no Endpoints for `service/greet` (same-same for `service/uppercase`):
```
kubectl describe service/greet
Name:              greet
Namespace:         kube-system
Labels:            app=greet
Annotations:       <none>
Selector:          app=greet
Type:              ClusterIP
IP:                10.152.183.63
Port:              <unset>  8080/TCP
TargetPort:        8080/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

kubectl describe service/uppercase
Name:              uppercase
Namespace:         kube-system
Labels:            app=uppercase
Annotations:       <none>
Selector:          app=uppercase
Type:              ClusterIP
IP:                10.152.183.94
Port:              <unset>  8080/TCP
TargetPort:        8080/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

**Comment by DazWilkin** [comment]
The Pod(s) aren't getting ClusterIPs which, I assume, is the more fundamental issue; no ClusterIP, means the Pod can't be bound by a Service.

> **NOTE** This is very possibly related to my configuration using MicroK8s.

```
kubectl get pods --output=wide
NAME        READY   STATUS    IP          NODE
greet       1/1     Running   <none>      krustlet
kuard       1/1     Running   10.1.1.25   workstation
uppercase   1/1     Running   <none>      krustlet
```
> **NOTE** Edited for clarity

**Comment by bacongobbler** [comment]
correct. In the meantime, you can `curl localhost:8080` from the same machine running krustlet to reach the endpoint. Right now the waSCC runtime starts the webassembly modules. They're just not hooked up to the cluster.

**Comment by DazWilkin** [comment]
Aha! This would be useful to add to the architectural overview (diagram).

This explains why I receive address in use errors. Unfortunately, I've an older version of MicroK8s that expose the kube-apiserver on :8080. So, if the Krustlet is attempting to spawn the waSCC runtime on :8080 (?) that explains more of my problems.

IIUC, waSCC on 8080 is not (currently) configurable.

I'm going to try to reconfigure MicroK8s to drop the insecure port for kube-apiserver.

Thanks!

**Comment by bacongobbler** [comment]
> IUC, waSCC on 8080 is not (currently) configurable.

Just change the container port to something other than 8080: https://github.com/deislabs/krustlet/blob/6d2cbfe119cf893761a09c527189dfbec29f5177/demos/wascc/greet/greet-wascc.yaml#L16

**Comment by DazWilkin** [comment]
Thank you!

IIUC the `"wascc:http_server"` is being bound to the environment variable value `PORT` provided by the container. So line 14 sets the runtime port and line 16 exposes it, correct?

```YAML
  containers:
    - image: webassembly.azurecr.io/greet-wascc:v0.4
      imagePullPolicy: Always
      name: greet
      env:
        - name: PORT
          value: "7777"
      ports:
        - containerPort: 7777
```
Then:
```
curl http://localhost:7777
{"method":"GET","path":"/","query_string":"","body":[]}

curl http://localhost:7777/freddie?hello
{"method":"GET","path":"/freddie","query_string":"hello","body":[]}
```

It would be useful to document this too.

I'm happy to do so if I understand it correctly.

**Comment by bacongobbler** [comment]
Ah yeah forgot about that. You're right on that. Thanks for finding that out.

**Comment by jose-acevedoflores** [comment]
Not sure if this is the right spot but it might be a good idea to add to the MicroK8s Prerequisites that you need the '--enable-bootstrap-token-auth' flag on 1.18 for the kube-apiserver. I installed MicroK8s through snap so it was a simple entry to /var/snap/microk8s/current/args/kube-apiserver. I was having trouble with the wasi demos getting a 401 Unauthorized when attempting to apply the CertificateSigningRequest and it wasn't obvious to me that flag was the issue.

**Comment by bacongobbler** [comment]
We’d love a microk8s guide in the how-to guide section of our documentation if you have the time to write one up. :)

https://github.com/deislabs/krustlet/tree/master/docs/howto

**Comment by bacongobbler** [comment]
closing as the krustlet-wasmcloud provider has been moved to its own project: https://github.com/wasmCloud/krustlet-wasmcloud-provider

Please open tickets related to the wasmclou provider there. Thanks.
