### ISSUE TITLE
Support auto-injection of wascc capabilities

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#248]
A compiled wascc actor exposes what capabilities it requires. The wascc provider should handle automatic injection of these dependencies where possible. Some considerations:

- Is there a way to "bundle up" the needed capabilities with an application
- Which capabilities should we expose by default?
- How can we expose the ability for users to provide their own capabilities?

**Comment by amar123deep** [comment]
It will be nice to provide atleast the messaging capability `wascc:messaging` to build a distributed application. Also I totally agree that there should be a way to add/expose custom capabilities.

Also, newer version of wascc supports `lattice`. How to switch on this feature?

**Comment by thomastaylor312** [comment]
We are working through how we'd like to handle the lattice feature within Krustlet. We have played around with it, but nothing is solid yet

**Comment by bacongobbler** [comment]
closing as the krustlet-wasmcloud provider has been moved to its own project: https://github.com/wasmCloud/krustlet-wasmcloud-provider

Please open tickets related to the wasmcloud provider there. Thanks.
