### ISSUE TITLE
FileModuleStore should respect imagePullPolicy=Always, 'latest' tag, or no tag

### ISSUE THREAD

**Issue by peterhuene** [deislabs/krustlet#256]
Currently `FileModuleStore` caches modules pulled from a registry.

However, it does not force a pull when `imagePullPolicy` is set to `Always` or when there is no `imagePullPolicy` specified and the image tag is `latest` or there is no tag.

[According to the documentation](https://kubernetes.io/docs/concepts/configuration/overview/#container-images), this should force a pull of the image from the repository.

We should also respect the other defaults for the image pull policy as specified in the documentation.

**Comment by thomastaylor312** [comment]
Ah yes, we still haven't checked for pull policy stuff. Thanks for bringing this up

**Comment by itowlson** [comment]
Anyone looking at this or shall I grab it?

**Comment by thomastaylor312** [comment]
Go ahead and grab it @itowlson!

**Comment by bacongobbler** [comment]
Go right ahead :)

@thomastaylor do you know if your work on #278 might be a blocker for this work? Trying to figure out what's the entrypoint here to detect when an event comes in reporting that the workload resource manifest changed.

**Comment by thomastaylor312** [comment]
It would likely result in a rebase either way, but they don't intersect directly
