### ISSUE TITLE
add container arguments support

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#258]
```bash
echo `
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-wasi-rust
data:
  myval: "cool stuff"
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-wasi-rust
spec:
  containers:
    - name: hello-world-wasi-rust
      image: webassembly.azurecr.io/hello-world-wasi-rust:v0.1.0
      args:
        - arg1
        - arg2
      env:
        - name: FOO
          value: bar
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONFIG_MAP_VAL
          valueFrom:
            configMapKeyRef:
              key: myval
              name: hello-world-wasi-rust
  tolerations:
    - key: "krustlet/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
' | kubectl apply --filename=-
```
Then 

```bash
kubectl logs pod/hello-world-wasi-rust
hello from stdout!
hello from stderr!
CONFIG_MAP_VAL=cool stuff
FOO=bar
POD_NAME=hello-world-wasi-rust
Args are: []
```

If I run the sample locally, it works as expected:

```
cargo run arg1 arg2
   Compiling hello-world-rust v0.1.0 (/tmp/krustlet/demos/wasi/hello-world-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/hello-world-rust arg1 arg2`
hello from stdout!
hello from stderr!
CARGO=...
CARGO_HOME=...
CARGO_MANIFEST_DIR=/tmp/krustlet/demos/wasi/hello-world-rust
CARGO_PKG_AUTHORS=Taylor Thomas <taylor.thomas@microsoft.com>
...
Args are: ["target/debug/hello-world-rust", "arg1", "arg2"]

```

**Comment by peterhuene** [comment]
It appears that the argument passing [isn't currently implemented yet](https://github.com/deislabs/krustlet/blob/master/crates/wasi-provider/src/lib.rs#L145).

**Comment by DazWilkin** [comment]
Thank you!

Perhaps this should be noted in the "hello world" demos that attempt to include args in their output?

**Comment by peterhuene** [comment]
It'd probably be easier just to implement it 😄.  The information is in the container spec, it just needs to be passed through to `WasiRuntime`.

**Comment by thomastaylor312** [comment]
Yeah, the argument support is there, just have to pass them through. The harder implementation will be calling a specific "command" which would need to be an exported function in wasm

**Comment by bacongobbler** [comment]
Marking as a good first issue, as all the wiring is in place. We just need to pass along the container arguments to wasmtime.

**Comment by itowlson** [comment]
I have this under way for WASI, but I'm not sure how to map it to WASCC, which as far as I can tell receives actor parameters in a different way.  Am I missing something, or should the WASCC provider merely discard any arguments in the container YAML?  If discard: silently, with a log, or fail with an error?

**Comment by thomastaylor312** [comment]
@bketelsen Do you know if there is anything wascc does that would support this or would that be another capability we need to add that sends arguments as events?

**Comment by bketelsen** [comment]
This doesn’t make any sense in the waSCC world.  Actors have configurations provided as a map, it’s possible to pass args through into that map if the wiring was put in place, but I’m not sure I see any benefit.
