### ISSUE TITLE
Determine how to handle container arguments in WASCC

### ISSUE THREAD

**Issue by itowlson** [deislabs/krustlet#282]
A Kubernetes Pod resource can specify arguments for each of its containers.  The WASI provider passes these to the WASM module via the WASI-defined interface.

However, there is no obvious mapping from command line arguments to the WASCC actor model.  We should determine whether to:

* Map container arguments to actor data in some Krustlet-specific way
* Drop container arguments on the floor
  * Silently?
  * Or with a log message?
* Error if container arguments are provided because we can't honour them

And then whatever we decide we should do it.

**Comment by bacongobbler** [comment]
I believe it is better if the provider errors out if container arguments are provided.

Taking an example...

1. Kubernetes 1.100 introduces a new image pull policy: `Sometimes`
1. krustlet-wasi and krustlet-wascc do not support this new policy
1. I create a WASI pod, declaring `imagePullPolicy: "Sometimes"`

If we silently dropped this error, we would also silently default to the default policy. Then, in a new Krustlet update when we support that policy, we would start respecting that new pull policy. This situation would result in us silently defaulting to a policy the workload did not expect, then silently switching over to the expected policy in an update. Is that better or worse for the user than erroring out until we support the `Sometimes` image pull policy?

In more general terms, it would be nice if there's a way we can validate resources incoming from Kubernetes in a provider, erroring out in a generic fashion if the provider cannot handle the input.

**Comment by itowlson** [comment]
+1 for validating and failing things we can't process - this is better than silently ignoring them and so doing something the user did not expect and may not have desired.

```yaml
containers:
- image: drevil/melt-pittsburgh:0.3
  args:
  - --dry-run
```
