### ISSUE TITLE
Wat

### ISSUE THREAD

**Issue by mkrupczak3** [deislabs/krustlet#3]
![wat](https://vignette.wikia.nocookie.net/aftertheflash/images/9/90/Wat_png_by_katysz_by_katysz-d6j542d.png/revision/latest?cb=20150729020554 "")

So, is this basically a rust-implemented kubelet variant for running server-side WASM code? I am confused.

**Comment by technosophos** [comment]
Yes. With the WASI or waSCC extensions.
