### ISSUE TITLE
bump wascc-host to 0.10

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#315]
There will be a wascc-host 0.10 release coming out later this week. When that's available we should bump to the next release and introduce lattice support (should be as easy as adding`features = ["lattice"]` to wascc-provider's Cargo.toml)

**Comment by autodidaddict** [comment]
Just a heads up that once you compile in lattice mode, a connection to nats or a nats leaf node is mandatory at startup. Thankfully, deploying a nats container is super easy.
