### ISSUE TITLE
Proper node configuration

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#34]
Right now, Krustlet uses a bunch of hardcoded values for creating the `Node` object in Kubernetes (such as the IP address and hostname). We should follow similar patterns to normal kubelet for configuring these values, so part of this task will be investigating how kubelet does it in mainline Kubernetes.

**Comment by technosophos** [comment]
Okay, so I chatted with some of the AKS Engine team about this. They configure via the `--address` flag on Kubelet. There is a "standard" configuration file format for Kubelet documented [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go), but it is definitely a lot of overhead.

Relevant references:

- Flags for kubelet: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
- Documentation for config: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
- AKS engine defaults: https://github.com/Azure/aks-engine/blob/5333968da5c2f2a3ec7582430b871646b20b106f/pkg/api/defaults-kubelet.go

**Comment by technosophos** [comment]
Note that using `0.0.0.0` is the standard practice there.

**Comment by thomastaylor312** [comment]
I also went and dug through the Kubelet codebase. The initial node configuration is found [here](https://github.com/kubernetes/kubernetes/blob/5ceddce53947ede00466f29d4ab66e88ffbd4fbd/pkg/kubelet/kubelet_node_status.go#L219) and you can basically override any of the IP and hostname values using a flag. The default node IP address comes from the system using the method found here: https://github.com/kubernetes/kubernetes/blob/61d36e4a43b831f960b190b81d371cb33b5f20d1/pkg/kubelet/nodestatus/setters.go#L189

I'll take this issue on and get an implementation in place
