### ISSUE TITLE
Wasmtime is mostly dead

### ISSUE THREAD

**Issue by LifeIsStrange** [deislabs/krustlet#351]
Mozilla has fired 25% of it's workforce a few days ago.
Among them, some rust core team members and all wastime paid devs have been fired.

**Comment by peterhuene** [comment]
Not only is it factually incorrect regarding the Wasmtime developers at Mozilla (of which I am still one), Wasmtime is a Bytecode Alliance project and is maintained by a large number of contributors outside of Mozilla.

Even if this were the proper forum to discuss it, which it is absolutely not, please refrain from spamming repositories with unactionable issues like this one.

**Comment by LifeIsStrange** [comment]
*Not only is it factually incorrect regarding the Wasmtime developers at Mozilla (of which I am still one)* great, I didn't know that. It does not confirm that wasmtime will get enough resources to achieve its goals but still is a reassuring information.

*Wasmtime is a Bytecode Alliance project and is maintained by a large number of contributors outside of Mozilla.* same answer, I wonder how active are other sponsors (red hat, Intel, etc)

*Even if this were the proper forum to discuss it, which it is absolutely not*
It absolutely is and is obvious to understand:
Krustlet use wasmtime as a dependency and therefore if wasmtime were to be compromised, then Krustlet would be too. 

*spamming* spamming something require to repeat a nuisible or at best useless action, here the action is useful (information sharing in case we're Krustlet devs weren't aware of the state of affairs) and most importantly isn't a repetition of an already done action and therefore, obviously, doesn't qualify at all as spamm.

But yeah the issue can be kept closed if you reasonably assume that wasmtime requirements aren't compromised which is epistemologically uncertain for an outsider, but as a moz intern I guess that you know more.

Regards, 
LifeIsStrange

**Comment by bacongobbler** [comment]
I am going ahead and locking this thread as this discussion is neither constructive, actionable, nor helpful.

But to be totally clear on our stance - as peter mentioned earlier - wasmtime is maintained by a larger group of contributors as part of the ByteCode Alliance. While we are sad to hear about the layoffs at Mozilla, that does not mean that wasmtime is “mostly dead”. We are quite confident that the project continues to be a valuable project to the WebAssembly community, and we will continue to use, provide feedback, and continue to contribute to the wasmtime community. It is also likely that the maintainers who were previously working on wasmtime for Mozilla will find new employment opportunities from companies looking to continue investing in wasmtime.
