### ISSUE TITLE
How configuration of wascc host is handled by krustlet 

### ISSUE THREAD

**Issue by amar123deep** [deislabs/krustlet#352]
wascc host needs to be configured by adding actor as well as capabilities to the host. One also needs to pass binding between the actor and the capability as shown in the [tutorial](https://wascc.dev/tutorials/first-actor/create_host/). 

How one can pass configurations, such as binding between the actor (via its public key) to the capabilities (such as key-value store or wascc messaging capabilities) in krustlet?

**Comment by bacongobbler** [comment]
This is performed automatically via krustlet. The actor requests certain capabilities like `wascc::logging` or `wascc::filesystem` and Krustlet exposes Kubernetes's capabilities through this system. For example, volume mounts are provided as `wascc::filesystem` capabilities, and Services are provided as `wascc::http` capabilities.

**Comment by bacongobbler** [comment]
FYI: the ticket on custom capabilities can be found here: https://github.com/deislabs/krustlet/issues/248
