### ISSUE TITLE
handling image from insecure registry

### ISSUE THREAD

**Issue by amar123deep** [deislabs/krustlet#356]
I set up a local registry with [kind](https://kind.sigs.k8s.io/docs/user/local-registry/). I pushed web assembly image via wasm-to-oci, but wasn't able to deploy the workload via kubectl. kubectl describe pod POD_NAME points to error message that krustlet is using https instead of http. 

`Message:      error sending request for url (https://localhost:5000/v2/): error trying to connect: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:332:`

**Comment by thomastaylor312** [comment]
Thanks for reporting this @amar123deep! So we definitely have support for this in the underlying OCI library, but we haven't exposed a flag to allow insecure registries. I am going to label this as an enhancement and we'll see if we pull this in to 0.5

**Comment by itowlson** [comment]
Can we run through the desired behaviour?  There are a few possibilities:

1. A configuration option which tells the kubelet to _always_ use insecure HTTP for registry pulls. This would be very simple to implement and would likely address @amar123deep's local dev scenario, but it a very blunt instrument.

2. A configuration option which tells the kubelet to _fall back_ to insecure HTTP if secure HTTPS fails.  So if this were set then kubelet would always initially use HTTPS for image pulls, but if that failed (and the option was set) it would retry using HTTP.  This might be a bit trickier to implement, but would allow the kubelet to work with both local HTTP and remote HTTPS registries.  Slightly concerned that it could make it _look_ like remote registry access was secure, while in fact an attacker could force a silent switch to HTTP without the user knowing.

3. A configuration option which tells the kubelet to use HTTP for _specific_ registries, while continuing to use HTTPS for all other registries.  This is more complex than option 1, but might still work out a bit simpler than option 2, and allows the kubelet to pull from both local HTTP and remote HTTPS registries with full server verification on the latter.

My suggestion would be option 3 but I'd like feedback (including other options) before diving in!  Thanks!

**Comment by thomastaylor312** [comment]
I think you are correct @itowlson. Number 3 is the best and most robust option. I don’t know that the actual kubelet has that option, but I think we should.

**Comment by itowlson** [comment]
@amar123deep Would you have a moment to try out #359 and see if it works for you?  My unit tests are passing but I'm not sure how to integration-test it.  Just add `--insecure-registries <your-registry-name>` to the krustlet command line options.  Thanks!

**Comment by amar123deep** [comment]
Sure @itowlson!

**Comment by amar123deep** [comment]
I tried the branch, but somehow it's failing due to the following reason (output of `kubectl describe pod POD_NAME`):
`Warning  FailedScheduling  16s (x2 over 16s)  default-scheduler  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taint {kubernetes.io/arch: wasm32-wascc}, that the pod didn't tolerate.`

**Comment by itowlson** [comment]
@amar123deep You might need to update your pod spec, there is a breaking change merged on this branch (from an earlier PR, not related to this one) - your pod now needs to tolerate `kubernetes.io/arch` rather than `krustlet/arch`.  Looks like the uppercase demo pod spec in main has this but perhaps you had an older version lying around?  Otherwise @thomastaylor312 this sounds related to your architecture cleanup PR - can you shed any light?

**Comment by thomastaylor312** [comment]
@itowlson I just tested this on `master` and the demo works properly. I also tested with your PR and it works fine. So maybe you have an old copy @amar123deep?

**Comment by amar123deep** [comment]
Thanks @itowlson! It works fine with local (insecure) as well as azure registries. I had an old copy causing the above mentioned issue.
