### ISSUE TITLE
Pre-compiled ARM binaries

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#358]
As a user, I would like to be able to download `aarch64` prebuilt binaries so I can run Krustlet on 64 bit ARM devices (like Raspberry Pi).

Other notes:

We may also want to have an "openssl-less" ARM binary to make it easier to just drop in on an embedded device

**Comment by jiayihu** [comment]
Is there anything specific that blocks krustlet from being used in ARM32? I'm evaluating it for usage with a STM32F429 board with 2MB Flash and 192KB RAM

**Comment by thomastaylor312** [comment]
Right now it is a limitation of what `wasmtime` and `wasm3` (the runtimes we are using) can compile to. I am pretty sure they only have the instruction sets for ARM64 (when they execute wasm). @bacongobbler is that correct?

**Comment by bacongobbler** [comment]
wasmtime cannot be compiled to arm32 at this time due to https://github.com/bytecodealliance/wasmtime/issues/339. wasm3 should be able to run on an ARM device as per their README:

> wasm3 runs on a wide range of architectures (x86, x86_64, ARM, RISC-V, PowerPC, MIPS, Xtensa, ARC32, ...) and platforms:

The tricky part will be building a hex file where you can run Krustlet on that STM32. That will likely require a custom provider. I would recommend looking into the AVR Rust project: https://github.com/avr-rust/

**Comment by bacongobbler** [comment]
It looks like AVR Rust has been merged into core, so it should be much simpler to experiment with now! https://www.avr-rust.com/#installation-rustup

**Comment by jiayihu** [comment]
Didn't understand the part about AVR-rust, isn't AVR just another kind of board such as STM32? For the latter there is already [stm32-rs](https://github.com/stm32-rs/stm32-rs). About the custom provider, I was more thinking about building a runtime based on [RTIC](https://github.com/rtic-rs/cortex-m-rtic), which in turn is based on Ada Ravenscar, and it has low footprint while allowing concurrency. Then I'd like to integrate wascc o something similar, but no-std and maybe more minimal, as WASM runtime and finally krustlet

**Comment by bacongobbler** [comment]
Sounds interesting. Let us know what you find out!
