### ISSUE TITLE
Refactor Pod::queue

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#374]
In Pod::queue, there's a huge method for running the Pod: [`run_pod`](https://github.com/deislabs/krustlet/blob/3cf9b9c0dac33a1cff1060b48a61eeceaaeebfe5/crates/kubelet/src/pod/queue.rs#L36). We should look into refactoring this code to make it a little simpler to read.

**Comment by thomastaylor312** [comment]
This ideally will be taken care of when I pull in the `kube_runtime` crate

**Comment by thomastaylor312** [comment]
This was taken care of in #396
