### ISSUE TITLE
support more Transition options for more outgoing edges

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#375]
Right now, each state can only transition from one state to the next, or enter an Error state. There may be cases in the future where we may need to transition to one or more states, depending on the outcome of the current state.

**Comment by kflansburg** [comment]
FWIW, there is actually nothing stopping us from doing `Transition::Advance(Box<A>)` and `Transition::Advance(Box<B>)` in the same handler. Given this, I propose that the only options for Transition are `Continue` and `Complete`. I'm more or less fine with this relaxation, but my problem is that there is no way to enforce somewhere which edges exist. It would be nice to enforce that an edge trait to the outgoing states. I'm trying to come up with the least intrusive way to do that.
