### ISSUE TITLE
ref(wasi-provider): drop HashMap for field handles

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#384]
With the refactor, `handles` only holds one handle to the pod, with each container's handle part of the pod handle. The HashMap<String, Handle> can therefore be refactored to an `Option<Handle>`.

**Comment by kflansburg** [comment]
is this referencing `SharedPodState::handles`? That holds multiple handles and is needed for logging / exec.

**Comment by thomastaylor312** [comment]
Isn't the hash map shared across all pods?

**Comment by bacongobbler** [comment]
Yep
