### ISSUE TITLE
Deleting waSCC Pod Always Throws Volume Capability Error

### ISSUE THREAD

**Issue by kflansburg** [deislabs/krustlet#416]
```
Error while trying to stop pod greet: unable to remove volume capability: Error(MiscHost("No such capability"))
```

**Comment by kflansburg** [comment]
@thomastaylor312 It seems like this is caused by the actor not having the `FS_CAPABILITY`, so the volumes aren't actually mounted on start. Then, when terminating, we try to unmount the volume which causes a capability error. I'm confused why this capability isn't found, is this some issue with my local configuration? Or is this related to the `greet` pod specifically? Either way it seems like we should check the capabilities before trying to unmount volumes.

**Comment by thomastaylor312** [comment]
I think it is the greet pod not having the capability. We definitely should check if it has the capability before trying to load any volumes. This feels kinda related to #248
