### ISSUE TITLE
Implement a bare minimum OCI Registry pull client

### ISSUE THREAD

**Issue by technosophos** [deislabs/krustlet#42]
The only complete OCI Registry client I have found is written in Go. While we've had luck linking that into Rust, I think we might be able to implement a minimal pull mode _specifically_ for fetching WASM modules out of an OCI registry.

Out of scope for this minimal first version:

- push
- multi-layers (unless we find them necessary)
- TUF

**Comment by radu-matei** [comment]
The tag we are passing will eventually point to an OCI manifest similar to:

```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.wasm.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.wasm.content.layer.v1+wasm",
      "digest": "sha256:4c7915b4c1f9b0c13f962998e4199ceb00db39a4a7fa4554f40ae0bed83d9510",
      "size": 1624962
    }
  ]
}
```

So for reference, the only media types this minimal library will need to handle are:

- `application/vnd.wasm.config.v1+json` for the manifest
- `application/vnd.wasm.content.layer.v1+wasm` for the actual module

**Comment by bacongobbler** [comment]
Hey! Has anyone taken this one on? Happy to join in on the fun.

**Comment by rylev** [comment]
This was implemented in #48

**Comment by radu-matei** [comment]
Not quite, as #48 only pulls the _manifest_ of the artifact, and not the artifact  itself.

We still need to parse the manifest and download the layer corresponding to the module.

**Comment by technosophos** [comment]
I do have a PR that I hope to get finished up that has the blob pull as well. Just learning the Stream stuff so I do it right.

**Comment by rylev** [comment]
This is now done with #82
