### ISSUE TITLE
State function documentation makes it hard to get to errors

### ISSUE THREAD

**Issue by itowlson** [deislabs/krustlet#420]
There is a lot of documentation on states and functions, which is great, _but_... it means that when you want to see how to use something, or to look at an error in VS Code, you have a _lot_ of content that is essentially "should not compile" doc-tests to wade through.

Here's something I'm doing right now:

![image](https://user-images.githubusercontent.com/865538/95275891-37e0ba00-08a6-11eb-953e-1b8f4765e51c.png)

The error text is right at the bottom of that pop-up box.  But to see it I'm having to scroll past a _lot_ of `next` method documentation.  This is several "pages" into the popup and you can see I'm only half way to my error (which VS Code shows at the bottom)!

I'm all in favour of thorough documentation but perhaps we can move some of the "should not compile" tests and samples out to where they will be less intrusive.

(I agree this is a broader issue with the Rust VS Code extension, as other types also tend to pile very detailed documentation into this tiny popup; if we can't do anything about it then we should keep the thorough docs, but it would be nice to evaluate if we can move some of it out somewhere.)

**Comment by moose-consulting** [comment]
I suspect / agree that most of this should be reorganized to be module-level documentation. It makes sense for method docstrings to be limited to a few lines.

**Comment by kflansburg** [comment]
I suspect / agree that most of this should be reorganized to be module-level documentation. It makes sense for method docstrings to be limited to a few lines.

**Comment by kflansburg** [comment]
This was closed by #458
