### ISSUE TITLE
WASI Provider Restart Pod Issues

### ISSUE THREAD

**Issue by kflansburg** [deislabs/krustlet#429]
While evaluating WASI E2E tests where a container failed and the Pod restarted, there appears to be an error related to a dropped channel in the Registered state the first time around. I believe there may be some cleanup that needs to be done in the Error state in anticipation of returning to Registered state to try again.

**Comment by kflansburg** [comment]
We probably need to verify that this is still happening after #458

**Comment by kflansburg** [comment]
@thomastaylor312 I think I would like to close this. I'm not even 100% sure how to reproduce this in the original code, and this code was rewritten so much for the container state machine that the issue is likely moot.

My only thought here is that we could try to add test cases which cause failures at every possible point in the current WASI state machine, and then make sure that no unexpected warnings are emitted. IMO this would be very brittle.

**Comment by thomastaylor312** [comment]
Feel free to close whenever. 

As for your additional thought, I think that any cleanup can be handled in the `Error` state, can it not?

**Comment by kflansburg** [comment]
I think it would be handled in Error state, the question is how does the Provider define what "cleanup" means.
