### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [deislabs/krustlet#438]
Hello Krustlet team,

I'm one of the co-chairs of the CNCF SIG-Runtime, although the project seems experimental I think it would be great for you to present/discuss it at one of our meetings.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by thomastaylor312** [comment]
I think this would be a great idea! Let me go ahead and add it to the agenda. Are there any specific things you'd want us to focus on or just a general overview?

**Comment by raravena80** [comment]
A general overview and sample use cases would be great!  Thanks!

**Comment by bacongobbler** [comment]
thanks @raravena80!
