### ISSUE TITLE
Running Krustlet on Docker Desktop Mac OS X

### ISSUE THREAD

**Issue by david6983** [deislabs/krustlet#447]
For my project, I would like to:
- run krustlet on Docker Desktop on mac os x without using minikube, microk8s or kind.
- Then, my goal is to run krustlet on a kubernetes cluster provided by rancher 2.0.

Any idea, how can easily install krustlet ?

**Comment by bacongobbler** [comment]
Hi @david6983!

Have you had the chance to look through the HOWTO tutorials on running Krustlet using KinD, minikube, etc? Several of us are running and testing Krustlet on a macOS development environment and would be happy to help you out if you have any issues.

https://github.com/deislabs/krustlet/tree/master/docs

**Comment by bacongobbler** [comment]
With regards to Rancher 2.0, I do not believe we've tested that scenario yet. I would suggest trying out one of the HOWTO guides first before attempting to venture off the beaten path.

**Comment by david6983** [comment]
I am wondering why not using just Docker Desktop instead of all the solutions like microk8s, KinD, minikube and so on.

Docker Desktop is actually running a kubernetes cluster, why not just using it instead of using minikube for example ?

**Comment by bacongobbler** [comment]
Docker Desktop should work as well.

If you're having issues with a particular section of the docs, please feel free to [reach out on Slack](https://github.com/deislabs/krustlet#community-discussion-contribution-and-support). Happy to help you out there and figure out what parts of the guide are unclear or need further clarification.

**Comment by david6983** [comment]
in the krustlet-on-wsl2.md for example which look like the closest to a Docker Desktop Mac Os installation, I don't understand what are the .crt file (--cert-file) in this command

```
Since you are running locally, this step is important. Otherwise krustlet will pick up on your
# local config and not be able to update the node status properly
$ export KUBECONFIG=~/.krustlet/config/kubeconfig
$ krustlet-wasi --node-ip $mainIP --node-name krustlet --cert-file=~/.krustlet/config/krustlet.crt --private-key-file=~/.krustlet/config/krustlet.key --bootstrap-file=~/.krustlet/config/bootstrap.conf
```

I ran ./bootstrap.sh from krstulet directory but I don't have any .crt files

**Comment by bacongobbler** [comment]
Okay, I think I see what you're pointing at now. I think that's a stale section of the documentation that was accidentally missed when we introduced https://github.com/deislabs/krustlet/pull/275. Feel free to disregard those flags and use the following instead:

```
krustlet-wasi --node-ip $mainIP --node-name krustlet
```

The TLS bootstrap API will generate a certificate and private key for you. You should not need to worry about setting those flags.

**Comment by david6983** [comment]
is $mainIP the IP from `ifconfig en0` ?

**Comment by david6983** [comment]
When the program said: `BOOTSTRAP: received TLS certificate approval: continuing`, do I need to wait the program finish or is krustlet running as long as krustlet-wasi run ?

**Comment by bacongobbler** [comment]
https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-on-wsl2.md#step-1-determine-the-default-gateway

**Comment by bacongobbler** [comment]
> When the program said: `BOOTSTRAP: received TLS certificate approval: continuing`, do I need to wait the program finish or is krustlet running as long as krustlet-wasi run ?

At that point, krustlet is running. You can keep that running in that terminal, open a new terminal and start using the demo apps.

However, based on the error you provided in that image, it does not appear you generated a bootstrap config [as requested in step 2.](https://github.com/deislabs/krustlet/blob/master/docs/howto/krustlet-on-wsl2.md#step-2-get-a-bootstrap-config). You will need to generate a bootstrap file so that Krustlet can be issued a TLS certificate from Kubernetes.

**Comment by david6983** [comment]
IS krustlet running in a pod when the krustlet-wasi is running ?

**Comment by bacongobbler** [comment]
> [...] but the status of my pod is `ImagePullBackoff` if the repo is private. Is it allowed to use gitlab registry ?

Image pull secret support was implemented in https://github.com/deislabs/krustlet/pull/367. You'll need to provide an image pull secret along with the pod if you want to fetch the image from a private registry. See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ for more information.

> The pod is running but I get an issue in the logs

Hmm... That means the Kubernetes API server cannot reach krustlet. If you're running it from within the WSL2 instance, you will need to use that as the IP address. As the documentation described in step 1 (emphasis in bold)...

> The default gateway for most Docker containers is generally 172.17.0.1. This IP is only reachable, by default, from the WSL2 distro. **However, the eth0 host network is accessible from Windows, so we can use this IP address to connect to the WSL2 distro (where Krustlet is running).**

When you set the `--node-ip` flag, you're informing the Kubernetes API server what IP address Krustlet is listening on. So you need to determine where you're running krustlet, and how the API server can issue requests against Krustlet.

Hope that helps.

**Comment by david6983** [comment]
I am not using wsl2 since I am just using Docker Desktop on Mac Os X not windows

**Comment by bacongobbler** [comment]
Okay. Regardless you will need to determine what IP address to provide to the kuebrnetes API server so that it can make API requests against Krustlet. The output of `ifconfig en0` might be what you need.

**Comment by david6983** [comment]
> Okay. Regardless you will need to determine what IP address to provide to the kubernetes API server so that it can make API requests against Krustlet. The output of `ifconfig en0` might be what you need.

same issue using the inet IP address from `ifconfig en0`

And this is the logs from krsutlet-wasi:

<img width="815" alt="Screenshot 2020-11-10 at 23 07 01" src="https://user-images.githubusercontent.com/34489538/98739445-a6cf9800-23a9-11eb-97a2-99d1f17fbe18.png">

**Comment by bacongobbler** [comment]
Seems like the webassembly module provided failed to run - which demo were you using?

**Comment by david6983** [comment]
> Seems like the webassembly module provided failed to run - which demo were you using?

I am using my own demo code which is the one from [tutorial01.md](https://github.com/deislabs/krustlet/blob/master/docs/intro/tutorial01.md) in Rust, do you think it is because of my rust code ?

```
apiVersion: v1
kind: Pod
metadata:
  name: krustlet-demo
spec:
  containers:
    - name: krustlet-demo
      image: registry.gitlab.com/$author/krustlet-demo:latest
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"
```
k8s.yaml

```
use std::time::Duration;
use std::thread::sleep;

fn main() {
    loop {
        println!("Hello, World!");
        sleep(Duration::from_secs(5));
    }
}
```
main.rs

**Comment by david6983** [comment]
@bacongobbler , in the howto examples do I need the line below ?

```
export KUBECONFIG=~/.krustlet/config/kubeconfig
```

because I get an error if I defined this variable when I launch `krustlet-wasi`:

```
Error: Error loading kubeconfig: Failed to infer config.. cluster env: (Error loading kubeconfig: Unable to load in cluster config, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined), kubeconfig: (Error loading kubeconfig: Failed to read '"~/.krustlet/config/bootstrap.conf"': No such file or directory (os error 2))

Caused by:
    0: Failed to infer config.. cluster env: (Error loading kubeconfig: Unable to load in cluster config, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined), kubeconfig: (Error loading kubeconfig: Failed to read '"~/.krustlet/config/bootstrap.conf"': No such file or directory (os error 2))
    1: Error loading kubeconfig: Failed to read '"~/.krustlet/config/bootstrap.conf"': No such file or directory (os error 2)
    2: Failed to read '"~/.krustlet/config/bootstrap.conf"': No such file or directory (os error 2)
    3: No such file or directory (os error 2)
```

**Comment by bacongobbler** [comment]
> I get a `ERROR wasi_provider::states::registered] Cannot run kube-proxy`

that's fine. See #167. You can ignore that error.

**Comment by bacongobbler** [comment]
Looks like everything is OK here. Are there any other issues you're running into here, or do you think you have a good start to close this one out? We've gone a bit off the rails from the original topic so I'd like to continue this conversation in Slack unless there's some action item we can take here.

**Comment by david6983** [comment]
> Looks like everything is OK here. Are there any other issues you're running into, or do you think you have a good start to close out this ticket? We've gone a bit off the rails from the original topic so I'd like to continue this conversation in Slack unless there's some action item we can take here.

everything is ok, we can close this issue. Thank you very much for your help. I start to understand more and more krustlet now
