### ISSUE TITLE
Are the optional fields on Kubernetes API objects properly handled?

### ISSUE THREAD

**Issue by rylev** [deislabs/krustlet#46]
Because of the very loose nature of Kubernetes API definitions when it comes to nullability, the `k8s-openapi` crate wraps all fields in optional. We are currently handling this by generously using `unwrap_or_default` on the fields. Is this correct? Are there any times where fields not being set would be a fatal error or even a recoverable error?

**Comment by technosophos** [comment]
There are some fields that are "required" but still marked as optional throughoutt the k8s API. The ones I know of are:

- `kind`
- `metadata`
- `metadata.name`

Oddly enough, while the "group, version, kind" pattern Kubernetes uses suggests that `apiVersion` is a required filed, it is not in all cases required. (This is super weird, IMO, but the Go Kubernetes libraries support this behavior). It is, however, required when sending an object to the API server.

@thomastaylor312 and @bacongobbler may know of some others. Helm deals with this issue quite a bit.

**Comment by thomastaylor312** [comment]
I am pretty sure container names and image names are required as well. Kubernetes should be handling the validation so pod objects we get from the informer should be valid, but I never know for sure

**Comment by rylev** [comment]
The fields currently being used are:
## Pod
### metadata
* `pod.metadata.name`
* `pod.metadata.namespace`
* `pod.metadata.labels`
* `pod.metadata.annotations`
### Status
* `pod.status`
* `pod.status.host_ip`
* `pod.status.pod_ip`
### Spec
* `pod.spec.service_account_name`
* `pod.spec.containers`
* `pod.spec.node_selector`

## Node
### Metadata
* `node.metadata.uid`

Do we have a good idea on which of these are actually optional? Would it help for us to define our own `Pod` type that has these fields always set?

**Comment by thomastaylor312** [comment]
My problem with having a custom type is that we’d have to update it with every field we’d want to use when we started using it. For example we are going to add stuff to the status object soon. If we wanted to abstract away all the unwrapping, we could create a wrapper type with helper methods or run the pod through a validator beforehand

**Comment by thomastaylor312** [comment]
The other thing to note with the fields you’ve mentioned is that many of them are optional to a user creating the pod (pretty much everything but name and containers in the list above), but the API will add almost all of the rest of them by default. I believe we are only getting valid pods not missing fields because the informer is getting them from the API, but I don’t know about the edge cases

**Comment by rylev** [comment]
This is largely addressed by #73. With wrapping the K8s pod type we can at least making accessing the fields more convenient.

**Comment by thomastaylor312** [comment]
@rylev I think we can close this for now as we've addressed it as much as we need to
