### ISSUE TITLE
Fail to set up the environment in minikube  due to kube-proxy

### ISSUE THREAD

**Issue by chuiyunjun** [deislabs/krustlet#464]
I tried to install krustlet in a minikube inside ubuntu OS but failed.  

I installed minikube (v1.15), kubectl (client:v1.20.0, server:v1.19.4) and krustlet binary (v0.5.0).

When i  bootstrapped Krustlet and ran the command "KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file $HOME/.krustlet/config/bootstrap.conf" , i got the error message as below

ubuntu@krustlet-tasl:$ KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file $HOME/.krustlet/config/bootstrap.conf
BOOTSTRAP: TLS certificate requires manual approval. Run kubectl certificate approve krustlet-tasl-tls
BOOTSTRAP: received TLS certificate approval: continuing
[2020-12-09T21:39:08Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:13Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:18Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:23Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:23Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:28Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:33Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:38Z ERROR wasi_provider::states::registered] Cannot run kube-proxy

The complete script after i initialized a VM with ubuntu 18.04 is as below .

ubuntu@krustlet-tasl:$ sudo apt update
<truncate output>
ubuntu@krustlet-tasl:$ sudo apt upgrade -y
<truncate output>
ubuntu@krustlet-tasl:$ services="
 docker
 "
ubuntu@krustlet-tasl:$ for service in ${services}; do
     service_dir="/etc/systemd/system/${service}.service.d/"
     sudo mkdir -p ${service_dir}
     cat << EOT | sudo tee "${service_dir}/proxy.conf"
 [Service]
 Environment="HTTP_PROXY=${http_proxy}"
 Environment="HTTPS_PROXY=${https_proxy}"
 Environment="NO_PROXY=${no_proxy}"
 EOT
 done
<truncate output>
ubuntu@krustlet-tasl:$ sudo systemctl daemon-reload
ubuntu@krustlet-tasl:$ sudo iptables -P FORWARD ACCEPT
ubuntu@krustlet-tasl:$ curl -fsSL https://get.docker.com -o get-docker.sh
ubuntu@krustlet-tasl:$ sudo sh get-docker.sh
<truncate part of output>
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:44 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
<truncate part of output>
ubuntu@krustlet-tasl:$ sudo usermod -aG docker ubuntu
ubuntu@krustlet-tasl:$ exit
logout
######################
I logged in again.
#######################
ubuntu@krustlet-tasl:$ docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
ubuntu@krustlet-tasl:$ curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.1M  100 19.1M    0     0  2948k      0  0:00:06  0:00:06 --:--:-- 2964k-i minikube_latest_amd64.deb
ubuntu@krustlet-tasl:$ sudo dpkg -i minikube_latest_amd64.deb
Selecting previously unselected package minikube.
(Reading database ... 91045 files and directories currently installed.)
Preparing to unpack minikube_latest_amd64.deb ...
Unpacking minikube (1.15.1) ...
Setting up minikube (1.15.1) ...
ubuntu@krustlet-tasl:$ minikube start --driver=docker
<truncate output>
ubuntu@krustlet-tasl:$ kubectl get po
No resources found in default namespace.
ubuntu@krustlet-tasl:$ bash <(curl https://raw.githubusercontent.com/deislabs/krustlet/master/docs/howto/assets/bootstrap.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2378  100  2378    0     0  21423      0 --:--:-- --:--:-- --:--:-- 21423
secret/bootstrap-token-309dc0 created
Switched to context "minikube".
Context "minikube" renamed to "tls-bootstrap-token-user@kubernetes".
User "tls-bootstrap-token-user" set.
Context "tls-bootstrap-token-user@kubernetes" modified.
Context "tls-bootstrap-token-user@kubernetes" modified.
ubuntu@krustlet-tasl:$ KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file $HOME/.krustlet/config/bootstrap.conf
krustlet-wasi: command not found
ubuntu@krustlet-tasl:$ wget https://krustlet.blob.core.windows.net/releases/krustlet-v0.5.0-linux-amd64.tar.gz
--2020-12-09 21:37:54--  https://krustlet.blob.core.windows.net/releases/krustlet-v0.5.0-linux-amd64.tar.gz
Connecting to 10.213.96.52:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 20866230 (20M) [application/x-tar]
Saving to: ‘krustlet-v0.5.0-linux-amd64.tar.gz’

krustlet-v0.5.0-linux-amd64.tar.gz  100%[===================================================================>]  19.90M  2.10MB/s    in 12s

2020-12-09 21:38:06 (1.67 MB/s) - ‘krustlet-v0.5.0-linux-amd64.tar.gz’ saved [20866230/20866230]

ubuntu@krustlet-tasl:$ tar -xzf krustlet-v0.5.0-linux-amd64.tar.gz
ubuntu@krustlet-tasl:$ mv krustlet-wasi /usr/local/bin/
mv: cannot move 'krustlet-wasi' to '/usr/local/bin/krustlet-wasi': Permission denied
ubuntu@krustlet-tasl:$ sudo mv krustlet-wasi /usr/local/bin/
ubuntu@krustlet-tasl:$ KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file $HOME/.krustlet/config/bootstrap.conf
BOOTSTRAP: TLS certificate requires manual approval. Run kubectl certificate approve krustlet-tasl-tls
BOOTSTRAP: received TLS certificate approval: continuing
[2020-12-09T21:39:08Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:13Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:18Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:39:23Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:23Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:28Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-09T21:40:33Z ERROR wasi_provider::states::registered] Cannot run kube-proxy

Does anyone know the reason? Thanks for any help.

**Comment by bacongobbler** [comment]
The errors about “Cannot run kube-proxy” are expected and can be safely ignored. See https://github.com/deislabs/krustlet/issues/167

Can you see your node available with `lube to get nodes`?

**Comment by chuiyunjun** [comment]
The output is like this.

ubuntu@krustlet-tasl:~$ kubectl get node
NAME            STATUS     ROLES    AGE   VERSION
krustlet-tasl   NotReady   <none>   16h   0.5.0
minikube        Ready      master   16h   v1.19.4

**Comment by bacongobbler** [comment]
Is krustlet currently running? Looks like it’s in the “NotReady” state... Usually indicates you shut down the node.

Usually you can determine the reason using `kubectl get node krustlet-tasl -o yaml`.

**Comment by chuiyunjun** [comment]
Thanks. Now i have both nodes running. but i got a new problem. Do i need to configure anything else between Step 2 and Step 3 in https://github.com/deislabs/krustlet/blob/master/docs/intro/quickstart.md?

ubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ krustlet-wasi --node-ip 172.25.0.52 --cert-file=/home/ubuntu/.krustlet/config/krustlet.crt --private-key-file=/home/ubuntu/.krustlet/config/krustlet.key --bootstrap-file=/home/ubuntu/.krustlet/config/bootstrap.conf
[2020-12-10T15:02:02Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
[2020-12-10T15:02:07Z ERROR wasi_provider::states::registered] Cannot run kube-proxy
^Cubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ubectl get node
NAME            STATUS   ROLES    AGE   VERSION
krustlet-tasl   Ready    <none>   17h   0.5.0
minikube        Ready    master   17h   v1.19.4
ubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ kubectl apply -f greet-wasi.yaml
Error from server (Forbidden): error when creating "greet-wasi.yaml": pods "greet" is forbidden: pod does not have "kubernetes.io/config.mirror" annotation, node "krustlet-tasl" can only create mirror pods
ubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ kubectl get node
NAME            STATUS   ROLES    AGE   VERSION
krustlet-tasl   Ready    <none>   17h   0.5.0
minikube        Ready    master   17h   v1.19.4

**Comment by chuiyunjun** [comment]
Another problem: The node will become from ready to notready after a while automatically, although i did nothing. 

ubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ kubectl get node
NAME            STATUS   ROLES    AGE   VERSION
krustlet-tasl   Ready    <none>   17h   0.5.0
minikube        Ready    master   17h   v1.19.4
ubuntu@krustlet-tasl:~/krustlet/demos/wasi/greet$ kubectl get node
NAME            STATUS     ROLES    AGE   VERSION
krustlet-tasl   NotReady   <none>   17h   0.5.0
minikube        Ready      master   17h   v1.19.4

**Comment by bacongobbler** [comment]
> Error from server (Forbidden): error when creating "greet-wasi.yaml": pods "greet" is forbidden: pod does not have "kubernetes.io/config.mirror" annotation, node "krustlet-tasl" can only create mirror pods

Interesting. The NodeRestriction admission plugin is responsible for enforcing that limitation to prevent nodes from creating pods that expand their access to resources like serviceaccounts and secrets unrelated to their existing workloads.

I have not heard that being enabled in prior minikube versions.

As for the sporadic flip-flopping between the Ready and NotReady states, this seems relevant:

> * message: Kubelet never posted node status.
>   reason: NodeStatusNeverUpdated

Let us know what you find out.
