### ISSUE TITLE
Has krustlet applied measures for containers isolation （like kata, firecracker）? 

### ISSUE THREAD

**Issue by chuiyunjun** [deislabs/krustlet#465]
same as title

**Comment by squillace** [comment]
hi @chuiyunjun, given that Krustlet runs web assembly modules and not containers, what measures did you have in mind?

**Comment by squillace** [comment]
pong, @chuiyunjun, just wanna make sure we understand the issue you have in mind.

**Comment by bacongobbler** [comment]
closing as unresponsive/inactive.
