### ISSUE TITLE
can krustlet run in the minikube with driver=none

### ISSUE THREAD

**Issue by flyflypeng** [deislabs/krustlet#476]
I want to run the krustlet with the minikube(minikube start with --drive none config) in my Linux VM, however, i can not run the krustlet-wasi successfully.

So I want to make sure krustlet is only supported with minikube(configured with --driver virtualbox)?

**Comment by thomastaylor312** [comment]
It should be able to work with most minikube configurations (and most "certified" k8s distributions as far as we know). So this could be a documentation issue of something else you need to configure. 

What kind of errors are you seeing? Can you let us know your Minikube, k8s, and krustlet version?

**Comment by bacongobbler** [comment]
hi @flyflypeng. Have you had a chance to test this out? We'd love to hear from you regarding the questions @thomastaylor312 asked earlier. Let us know!

**Comment by bacongobbler** [comment]
Closing as inactive. Let us know when you have any updates to share and we'll happily re-open this ticket. Thanks!
