### ISSUE TITLE
Extend Krator framework to enable it to react to changes to the watched object

### ISSUE THREAD

**Issue by soenkeliebau** [deislabs/krustlet#481]
**Proposed Enhancement**
I've looked the Krator crate to see whether we could use it as basis for our Kubernetes operators.

One limitation that I noticed is that the framework currently does not provide a method to allow reacting to changes to a watched object. In the current implementation of the state machine when the watched object in the apiserver changes it is updated in the shared state, but this in only exposed to client code after the next state transition. And to notice the implementation would have to keep a copy of the object and compare on every state transition.

This works well with pods, which are not usually updated, but rather deleted and recreated. However for operators the watched objects are normally patched, not recreated, which means that the state machine would need to be notified of these changes. I think this will be a frequent requirement and is worth offering as an optional function.

**Possible Implementations**
There are a couple of potential solutions that come to mind, I'll just list them here with no claim to completeness  or preference whatsoever:

- add an informer to the podstate that can be used to listen for changes - this is a workaround that wouldn't require changes to the framework
- copy the way that deletions are handled and notify state objects, I've played around a little and created a [test implementation](https://github.com/soenkeliebau/krustlet/commits/apply_notify) (not against Krator, but back when the code was still part of the Kubelet)
- allow stating a "reconcile-state" that is transitioned to automatically (Note: we may need to think about allowing to delay this transition in case the operator is currently doing something that shouldn't be interrupted)

I'm sure there are plenty more possible solutions, I'll leave it at that for now and see if other people think this is a legitimate need.

**Prior discussion:**

We've discussed this on the [slack channel](https://kubernetes.slack.com/archives/C015X72FV54/p1605741144159700) a little while ago, which I'm linking here for reference - I couldn't find a way to export the conversation, if anybody know of something for that please let me know and I'll attach an export to this ticket.

**Comment by kflansburg** [comment]
This was definitely a todo that I identified when I was creating the first PR. My current thought is that we could create a new `Notify` like you described which indicates that the object has been modified. We would also pass `Arc<Mutex<Object>>` to the state handler (this would have been a breaking API change which is why it was not included in the first PR). 

A fancier option would be to try to implement `Stream` for the type wrapping `Manifest`. 

In either case you could await any modifications and react accordingly. 

I agree that interrupting execution to transition to a reconciled state would cause a lot of issues (its another option I considered).

**Comment by soenkeliebau** [comment]
I agree that the notify should probably be entirely sufficient for most use cases.
One issue I noticed during my tests was that I kept getting notified over and over, I believe this was due to the changes being applied to the pod status when transitioning through the states triggered apply-events again, which cause me to transition -> again causing a status update etc.

One idea I had was to allow handing a closure into the framework which is called with old and new pod data for every event and can determine if a the change was _relevant_ and notify only be called if this returns true.

**Comment by kflansburg** [comment]
Regarding your first point, that was when testing a `modified` `Notify`, correct? Not with the current `master` branch?

On your second point, I think we could do something like that. We could also possibly generate a JSON diff to highlight the changes.

**Comment by soenkeliebau** [comment]
Yes indeed, should have clarified that, sorry. That was when I was playing around with the changed branch I linked in the issue which had the Notify that is triggered by apply events.

Regarding the json diff, that would probably come in handy, but might go against Kubernetes principles as I understand them :) 
If I'm not mistaken, a reconciliation should not care what has changed, but just look at the current state of the object. Granted, we'd already be cheating on this point by comparing before notifying, but I'd argue that that is more of a filter than anything used by real logic..

**Comment by thomastaylor312** [comment]
@soenkeliebau So in general, I am not in favor of doing a diff. I had a [discussion](https://github.com/clux/kube-rs/issues/266) with the `kube` crate maintainers about this and doing a diff kinda breaks the state machine/reconciliation paradigm. I know that the Go library does this and that plenty of other k8s things do as well, but the argument is that the reconciliation loop or state machine shouldn't need to know the previous state. What should be happening is that the reconciliation sees that current state doesn't match expected state and _reconcile_ current state to match expected. Having the old and new objects breaks that idea and leads to problems if events are dropped. 

So although I can be convinced otherwise, I would prefer to avoid the diff passing/old and new option

**Comment by thomastaylor312** [comment]
However, to be clear, I am totally on board with the idea of having something to notify if something is updated

**Comment by kflansburg** [comment]
I think we are aligned here. I had originally thought it would be useful to highlight the changes for the operator but if an update gets missed then this will cause problems.

**Comment by soenkeliebau** [comment]
I agree that we agree :)

Just to clarify my proposal though, I did not want to pass the pod diff into the reconciliation function. That should run purely based of the current pod object. The only thing I wanted to allow was to suppress triggering the reconciliation for certain changes - changes to the pod state in my example, because those lead to an infinite reconciliation loop for me, as every reconciliation triggered an update to the pod date, hence triggering the next reconciliation and so forth.

But I may have had a fundamental flaw in the way that I structured my code...

**Comment by kflansburg** [comment]
@soenkeliebau, I think the solution I plan to implement is either `Notify` or  some sort of `Stream`. This wont force a transition of states and generate a new status update unless you choose to do so. But you will be responsible for monitoring it within your state handlers. Does this seem reasonable?

**Comment by soenkeliebau** [comment]
@kflansburg I am sure that I can work with that!

I think my issue with the endless reconciliation loop was emphasized by the fact, that the Krustlet is watching pods and updating the status in pods at the same time. In contrast to this, an operator will probably watch some CRD and not might update the status of that CRD, but this will happen less often and probably only when actually performing changes.

I've drawn a couple of partial activity diagrams and thought about the entire state machine for reconciliation approach quite a bit in the past day, but I still struggle to put my thoughts into words to be frank..

I'll give it another try tomorrow - but anything I could write will not change the fact that what you are proposing is perfectly fine and usable!
