### ISSUE TITLE
Azure Deployment fails with RoleAssignmentUpdateNotPermitted error

### ISSUE THREAD

**Issue by DerekStrickland** [deislabs/krustlet#489]
@kflansburg 's last commit got us past the issue with the GitHub URL, but now it seems that something about the current deployment strategy approach isn't making Azure happy. I put in my public ssh key, sp id, and sp password as instructed, and now this error is being thrown. Not entirely sure what's going on but I will say I see some [hardcoded GUIDs here](https://github.com/deislabs/krustlet/blob/05e067d1736693c48c280566a4bb4f53dfbc1fff/contrib/azure/azuredeploy.json#L81) and that seems like it can't work for people outside your subscription. Maybe the template needs some custom role too?  Not sure.

I'm actually available most of the day today if I can help in any way (testing w/e). Also, let me know if Slack is preferred.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
  ]
}

**Comment by bacongobbler** [comment]
Hmm... When I was first reading the ARM documentation, those GUIDs should be present in every subscription, as they are a global GUID which represents the "contributor" and "listClusterUserCredential" roles, respectively.

**Comment by bacongobbler** [comment]
The source of these GUIDs came from the azure quickstart examples. You can see that the contributor role GUID is being used across multiple examples here: https://github.com/Azure/azure-quickstart-templates/search?q=b24988ac-6180-42a0-ab88-20f7382dd24c

**Comment by bacongobbler** [comment]
How did you create the service principal?

**Comment by DerekStrickland** [comment]
ah yeah I forgot that there were some global guids for system roles. 

@bacongobbler  I followed the instructions here in the how to for Azure guide. Specifically I used this command

`az ad sp create-for-rbac --name ServicePrincipalName --skip-assignment`

**Comment by bacongobbler** [comment]
Hey @DerekStrickland. Just checking in here to see if you determined what might be causing the issue or if you found any workarounds.

**Comment by DerekStrickland** [comment]
Hi @bacongobbler  I haven't. End of financial quarter was pretty busy. I'll see if I can get back to it this weekend.

**Comment by thomastaylor312** [comment]
@DerekStrickland Wanted to check back one more time here, any update on what caused the issue?

**Comment by DerekStrickland** [comment]
@thomastaylor312 Sorry! I've not had any time for this. I'll close this issue, and reopen if/when I run into it again.
