### ISSUE TITLE
Krustlet bootstrapping generates JSON rather than YAML kube configs (expect YAML)

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#491]
`krustlet-[wascc|wasi]` both create JSON format kube config files.

Although, YAML >> JSON, it is convention to use YAML for Kubernetes manifests.

```bash
KUBECONFIG=${PWD}/krustlet-config \
cargo run --bin=krustlet-wascc -- \
  --node-ip=127.0.0.1 \
  --node-name=krustlet \
  --bootstrap-file=${HOME}/.krustlet/config/bootstrap.conf

more ${PWD}/krustlet-config | jq .
```
Yields, e.g.:

```JSON
{
  "apiVersion": "v1",
  "clusters": [
    {
      "cluster": {
        "certificate-authority-data": "LS0tLS1C...",
        "server": "https://192.168.1.150:16443"
      },
      "name": "krustlet"
    }
  ],
  "contexts": [
    {
      "context": {
        "cluster": "krustlet",
        "user": "krustlet"
      },
      "name": "krustlet"
    }
  ],
  "current-context": "krustlet",
  "kind": "Config",
  "preferences": {},
  "users": [
    {
      "name": "krustlet",
      "user": {
        "client-certificate-data": "LS0tLS1C...",
        "client-key-data": "LS0tLS1C..."
      }
    }
  ]
}
```

**Comment by bacongobbler** [comment]
Is there a runtime issue with this format, or just a suggestion? Kubernetes accepts both formats, so it shouldn't really matter which format is generated to the end user.

**Comment by DazWilkin** [comment]
That's correct; it doesn't matter

But, conventionally, manifests (including configs) are YAML

**Comment by bacongobbler** [comment]
okay. Unless there's a specific issue with generating output as JSON then it's shouldn't really matter.

Besides, it's much faster to parse/unparse JSON over YAML, and the former is a subset of the latter so the two are compatible formats. :)

Thank you for your suggestions.
