### ISSUE TITLE
Lease creation fails

### ISSUE THREAD

**Issue by bketelsen** [deislabs/krustlet#5]
```[2020-02-28T20:11:41Z INFO  krustlet::node] created node just fine
[2020-02-28T20:11:41Z ERROR krustlet::node] Failed to create lease: ApiError BadRequest ("Lease in version \"v1\" cannot be handled as a Lease: v1.Lease.Spec: v1.LeaseSpec.RenewTime: unmarshalerDecoder: parsing time \"2020-02-28T20:11:41.636526400Z\" as \"2006-01-02T15:04:05.000000Z07:00\": cannot parse \"400Z\" as \"Z07:00\", error found in #10 byte of ...|36526400Z\"}}|..., bigger context ...|\":300,\"renewTime\":\"2020-02-28T20:11:41.636526400Z\"}}|...")
[2020-02-28T20:11:41Z INFO  krustlet::server] starting webserver at: V4(0.0.0.0:3000)
[2020-02-28T20:11:42Z ERROR krustlet::node] Failed to create lease: ApiError NotFound ("leases.coordination.k8s.io \"krustlet\" not found")```

**Comment by technosophos** [comment]
What Kubernetes distro are you using? I think I mainly tested on Kind

**Comment by technosophos** [comment]
THat date gets set in `node.rs`:

```rust
/// Defines a new coordiation lease for Kubernetes
///
/// We set the lease times, the lease duration, and the node name.
fn lease_spec_definition() -> LeaseSpec {
    LeaseSpec {
        holder_identity: Some(NODE_NAME.to_string()),
        acquire_time: Some(MicroTime(Utc::now())),
        renew_time: Some(MicroTime(Utc::now())),
        lease_duration_seconds: Some(300),
        ..Default::default()
    }
}
```

**Comment by bketelsen** [comment]
It was whatever the default on AKS is as of yesterday.   I’ll look in a bit.

Brian

On Mar 2, 2020, at 4:14 PM, Matt Butcher <notifications@github.com> wrote:

﻿

What Kubernetes distro are you using? I think I mainly tested on Kind

**Comment by bketelsen** [comment]
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bketelsen** [comment]
Now that we've updated the runtimes I can't reproduce this.  Will hold off a bit, but marking this as potentially solved.

**Comment by peterhuene** [comment]
I'm seeing this error with current master and docker desktop's k8s (version `1.15.5`):

```
[2020-03-05T20:23:12Z ERROR kubelet::node] Failed to create lease: ApiError  ("v1.Lease.Spec: v1.LeaseSpec.RenewTime: unmarshalerDecoder: parsing time \"2020-03-05T20:23:12.721Z\" as \"2006-01-02T15:04:05.000000Z07:00\": cannot parse \".721Z\" as \".000000\", error found in #10 byte of ...|3:12.721Z\"}}|..., bigger context ...|econds\":300,\"renewTime\":\"2020-03-05T20:23:12.721Z\"}}|...")
```

**Comment by technosophos** [comment]
@peterhuene and that was on the code from `master`? I had been wondering if we fixed the problem merely by updating the Kubernetes API library, but now I am thinking that is not the case. I'm back to thinking there must be some missed expectations of the format for the date stamp.

**Comment by peterhuene** [comment]
Yep, my HEAD is 88f7fc19ee7aac38a977aa18d74fc5548c1b2416.

**Comment by peterhuene** [comment]
After some restarts, it seemed to successfully acquire a lease, so my guess is it happened to work when now's microseconds were above 100000 so there were enough digits to parse (I'm assuming from my previous time above that it was omitting the leading 0s), perhaps?

**Comment by peterhuene** [comment]
And perhaps Brian's original issue was the current time was being sent with nanoseconds?

**Comment by technosophos** [comment]
Ah! I think @peterhuene is right.



Here's the Kube OpenAPI section responsible for that timestamp: https://github.com/Arnavion/k8s-openapi/blob/2192d65dcbc4ae0b4f1eec7d8669a97223261f04/src/v1_16/apimachinery/pkg/apis/meta/v1/micro_time.rs

And in the Go implementation: https://github.com/kubernetes/apimachinery/blob/b789a6e6b31f49e34cd0b0876791677a85bbb375/pkg/apis/meta/v1/micro_time.go

The Go time format is this: `const RFC3339Micro = "2006-01-02T15:04:05.000000Z07:00"`.

This Go code fails:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	dfmt := "2006-01-02T15:04:05.000000Z07:00"
	str := "2020-03-05T20:23:12.721000Z"
	out, err := time.Parse(dfmt, str)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("Date is: %s\n", out)
}
```

But this works fine:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	dfmt := "2006-01-02T15:04:05.000000Z07:00"
	str := "2020-03-05T20:23:12.721Z"
	out, err := time.Parse(dfmt, str)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("Date is: %s\n", out)
}
```
https://play.golang.org/p/VsAndZR-w4J

**Comment by peterhuene** [comment]
I think the problem might lie in the `k8s-openapi` crate's `MicroTime`'s serialization, which is delegating directly to `DateTime<Utc>` for serialization.  I think `DateTime<Utc>` formats itself as if `to_rfc3339` was called, which is going to format with `SecondsFormat::AutoSi`, which will use 3, 6, or 9 digits depending on whatever the nanoseconds is.

I think the `k8s-openapi` needs to be fixed to serialize with `to_rfc339_opt` and passing in `SecondsFormat::Micros`.

**Comment by peterhuene** [comment]
I'll file a bug upstream on `k8s-openapi`, but I think we should probably manually serialize the lease spec until that fix is made.

**Comment by rylev** [comment]
This is no longer an issue
