### ISSUE TITLE
Support for registries with HTTP basic authentication

### ISSUE THREAD

**Issue by ereslibre** [deislabs/krustlet#501]
:wave:, I'm currently using the `oci-distribution` crate latest release (0.4.0) and I have noticed that despite the API leads to think that you can [provide basic authentication](https://github.com/deislabs/krustlet/blob/9a6182276b1835daf641f0007f27b50dfd55343b/crates/oci-distribution/src/secrets.rs#L7-L8), the HTTP basic auth usual workflow (include the `Basic` `Authorization` header with every request, containing directly a base64'ed of the `username:password`).

Instead, it seems like internally the crate is conflating this with an OAuth2 approach, [where it tries reuse a previous token, or request a token and store it for future requests](https://github.com/deislabs/krustlet/blob/9a6182276b1835daf641f0007f27b50dfd55343b/crates/oci-distribution/src/client.rs#L144-L146).

I'm wondering if as a project you would be interested to support both authentication schemas clearly separated, or if this approach has a specific reason at this time.

I am very interested in following guidelines and potentially contribute this change myself if possible and desired.

Thank you for your time!

**Comment by bacongobbler** [comment]
Hey @ereslibre! We'd be happy to look at contributions looking to improve this workflow. It may be worth looking at the [distribution specification](https://github.com/opencontainers/distribution-spec) to see if there are any concrete details on how a client should handle these headers to discern between HTTP Basic authentication vs OAuth2 authentication.

Let us know what you find out!

**Comment by bacongobbler** [comment]
Hey @ereslibre! Just checking in here to see how things are going. Any progress updates you'd like to share?

**Comment by ereslibre** [comment]
Hello @bacongobbler! Let me have a look and I'll come back to this and give some feedback tomorrow. As you mentioned, the spec is not being specific about this. I wanted to have a look at some registries and see what are their implementations (e.g. I know the Docker distribution project allows basic auth access -- by pointing to an htaccess file), and wanted to check other implementations like harbor or quay. I don't have enough information right now to make an educated proposal.

As a first guess I think it's going to be hard to discern between auth strategies (like discovering what auth method can be used with each registry), but I think even if that's not possible the API of the oci-distribution crate can still be open to different auth methods (without having to discover the one it should use -- delegating this to the oci-distribution crate consumer), move the current behavior to an `OAuth2` enum value, and include other enum value `BasicAuth` that behaves like the regular basic auth (`auth.htpasswd` in the [Docker distribution config](https://docs.docker.com/registry/configuration/)).

I know it has been a while, but I am going to look into the other registries implementations and give an educated proposal, to see if that could match with your project goals.

**Comment by ereslibre** [comment]
Since the issue is minor because an OAuth2 registry authenticates properly, and this issue is only present for example, when uisng the docker distribution locally fwith htpasswd as the single source of truth for authentication, this is probably a minor issue.

I think it's worth closing this issue because there is not a real problem except if you are using registries with authentication that don't follow the OAuth2 spec (like the `htpasswd`-based docker registry).

I will submit a PR so we can separate both use cases on the oci-distribution crate for direct crate users, and we can discuss over there.

Thanks a lot!
