### ISSUE TITLE
[krator/master] status update not working anymore

### ISSUE THREAD

**Issue by kesselborn** [deislabs/krustlet#537]
after the tokio update, the status update doesn't work anymore for my code -- I did not update the function for the status update, so I guess it's related to the update?

**Comment by kflansburg** [comment]
Can you provide more information here? Are you referring to the status patch that occurs when a state is entered? Are any warnings emitted? I ran into some issues with CRDs which were patched in #530

**Comment by kesselborn** [comment]
mmm ... I guess I had a state before #530 then -- I can't recreate the problem anymore with master after switching back to the master branch and testing #538.
Closing this issue and keeping in mind to refresh master next time :) 
Thanks
