### ISSUE TITLE
Is crate oci-distribution 0.6.0 ready to publish?

### ISSUE THREAD

**Issue by stevelr** [deislabs/krustlet#543]
the repo for oci-distribution has tokio 1.0 support (yay!) but Cargo.toml in github still says 0.5.0, which is the pre-tokio-1.0 update. Is it ready to release the crate as 0.6.0 yet? This is blocking another project that has a tokio 1.0 dependency. Thanks! I can submit a PR if that would help.

**Comment by stevelr** [comment]
Thank you!!

**Comment by thomastaylor312** [comment]
@stevelr 0.6 is now live as of yesterday evening
