### ISSUE TITLE
Add Device Plugin support

### ISSUE THREAD

**Issue by kate-goldenring** [deislabs/krustlet#594]
Kubernetes' [Device Plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) framework enables Kubernetes workloads to request extended resources, such as hardware, advertised by Device Plugins. While krustlet currently supports CSI plugins, it does not support Device Plugins, as noted in its [documentation](https://github.com/deislabs/krustlet/blob/811fbf871ca7f6955d1018b6cb61db7670583c6b/docs/topics/plugin_system.md#what-is-not-supported).
In order to add support, three things must happen:
1. Investigation into how Kubernetes supports multiple plugin types
2. Reorganizing krustlet's kubelet crate to either match the Kubernetes approach and/or promote support for other types of plugins if more are added to Kubernetes in the future
3. Implementation! :partying_face:

### Investigation
In order to understand how to best add Device Plugin support to krustlet, I sifted through Kubernetes to understand how they are handling CSI and DP plugin support.

Upon startup, the Kubernetes kubelet [registers two Plugin Handlers](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/kubelet.go#L1403), one for CSI plugins and the other for for device plugins. Krustlet has currently implemented the equivalent of the CSI Plugin Handler as a `PluginRegistry` in its [`plugin_watcher` module](https://github.com/deislabs/krustlet/blob/main/crates/kubelet/src/plugin_watcher/mod.rs). The `PluginRegistry` implements both the [plugin registration API](https://github.com/kubernetes/kubelet/blob/v0.19.2/pkg/apis/pluginregistration/v1/api.proto) -- which despite its agnostic name, is not for Device Plugins -- and [`PluginHandler`](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/cache/types.go#L47) interface.

Kubernetes' kubelet has one [pluginManager](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/plugin_manager.go#L83) to which the CSI and DP `PluginHandlers` register. The [`pluginManager.reconciler`](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/reconciler/reconciler.go#L73) makes sure that all plugins are in the correct (registered or deregistered) state. For example, it checks to see if a socket no longer exists for a plugin that is in the registered plugin list of the`pluginManager.reconciler.actualStateOfWorld`. If so, it will [unregister the plugin](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/reconciler/reconciler.go#L116) by calling the associated `PluginHandler's` `deregisterPlugin` function.

Therefore, plugin management in Kubernetes consists of the following:

1. A single `PluginManager` maintains list of plugins and reconciles state of plugins.
2. CSI and DP `PluginHandlers`  implement the [`PluginHandler` interface](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/cache/types.go#L47), so the `PluginManager` can ask them to register/deregister plugins when reconciliation is needed.
3. CSI and DP plugins implement their own APIs for interacting with their plugins ([CSI plugin API](https://github.com/kubernetes/kubelet/blob/v0.19.2/pkg/apis/pluginregistration/v1/api.proto) and [Device Plugin API](https://github.com/kubernetes/kubelet/blob/v0.19.2/pkg/apis/deviceplugin/v1beta1/api.proto#L23).

The only shared code between the two `PluginHandlers` appears to be the reconciliation that happens by the `PluginManager`.

The CSI and DP `PluginHandlers` handle registration differently. CSI plugins advertise a `Registration` service that the kubelet CSI `PluginHandler` calls when it notices a new socket under `/var/lib/kubelet/plugins_registry/`. The inverse happens for DPs. The kubelet DP `PluginHandler` advertises a `Registration` service at `/var/lib/kubelet/device-plugins/kubelet.sock` that DPs call.

### Kubelet Proposed Restructuring
Currently, in krustlet, there is a `plugin_watcher` module that contains support for CSI plugins. It also contains a `PluginType` enum with both `CsiPlugin` and `DevicePlugin` options. However, the remaining code is specific to CSI plugin support. This `plugin_watcher` module may be best renamed `csi_plugin_handler` and moved to be a submodule under a `plugins` module. A new `device_plugin_handler` submodule would also live under the `plugins` module. The `plugin_watcher's` `valdiate`, `register`, and `remove_plugin` functions, which appear to be an implmentation of the [`PluginHandler` interface](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/cache/types.go#L47), can be moved to be an implementation of a `PluginHandler` trait, implemented in both the `csi_plugin_handler` and `device_plugin_handler` modules and called out to by the `plugin_manager`. 

>The Kubernetes' Device Plugin Manager implements the `PluginHandler` interface [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/cm/devicemanager/manager.go#L341).

The rust modules inside the krustlet kubelet (`./krustlet/crates/kubelet`) could be divided like so:
```
kubelet
└── src
    └── plugins
        ├── plugin_manager (reconciler)
        ├── plugin_handler_interface
        ├── reconciler
        ├── device_plugin_handler
        │   └── ...
        └── csi_plugin_handler
```
> Would these sub-modules be better named `device_plugin_manager` and `csi_plugin_manger`, since the `PluginHandler` interface is only a subset of the functionality they implement? They also each implement their plugin APIs in order to manage plugins. The name `PluginRegistry` works for CSI, since its [API](https://github.com/kubernetes/kubelet/blob/v0.19.2/pkg/apis/pluginregistration/v1/api.proto) is focused on registering the plugins; however, kubelet implements both the `Registration` service and device plugin client in the [Device Plugin API](https://github.com/kubernetes/kubelet/blob/v0.19.2/pkg/apis/deviceplugin/v1beta1/api.proto#L23).

Or, to better match the Kubernetes repository layout where plugins are placed under the directory of their area of concern:
```
kubelet
└── src
    ├── plugin_manager
    │   ├── plugin_handler_interface
    │   └── reconciler
    ├── cm (container manager)
    │   ├── device_plugin_handler 
    │   └── ... later add support for memory manager, topology manager, etc, as in K8s cm dir
    └── volume
        └── csi_plugin_handler

```
> Note: these are the K8s equivalent for the [`csi_plugin_handler`](https://github.com/kubernetes/kubernetes/blob/fd74333a971e2048b5fb2b692a9e043483d63fba/pkg/volume/csi/csi_plugin.go) and [`device_plugin_handler`](https://github.com/kubernetes/kubernetes/tree/fd74333a971e2048b5fb2b692a9e043483d63fba/pkg/kubelet/cm/devicemanager). 

This latter layout propses adding a directory for container managers (cm) as done in [Kubernetes](https://github.com/kubernetes/kubernetes/tree/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/cm). It contains the device plugin manager (equivalent to the `PluginHandler`), memory manager, topology manager, etc.

**Comment by thomastaylor312** [comment]
I think I completely agree with the rename and making sure this is all handled under a single `PluginRegistry` (which I believe is what you are saying the restructuring would look like? Please correct me if I am wrong here). Thank you so much for taking this on!

**Comment by thomastaylor312** [comment]
Going to note this as a breaking API change for now unless I read things wrong (in which case I'll remove). Going to put this into 1.0 since it is breaking

**Comment by kate-goldenring** [comment]
> I think I completely agree with the rename and making sure this is all handled under a single `PluginRegistry` (which I believe is what you are saying the restructuring would look like? Please correct me if I am wrong here). Thank you so much for taking this on!

I see that single managing entity as a `PluginManager` that handles the state of plugins and maintains a list of them, as done in [Kubernetes](https://github.com/kubernetes/kubernetes/tree/fd74333a971e2048b5fb2b692a9e043483d63fba/pkg/kubelet/pluginmanager). I believe the type `PluginRegistry` struct would be phased out and CSI and DP specific functionality would each go under their own `PluginHandler`.

So [this `Provider` method](https://github.com/deislabs/krustlet/blob/main/crates/kubelet/src/provider/mod.rs#L155) would likely change to be named `plugin_manager`.

**Comment by thomastaylor312** [comment]
Ok sweet. That sounds fine to me!

**Comment by kate-goldenring** [comment]
The device plugin manager hosts the registration service of the device plugin interface. After a device plugin (DP) calls [this `Register` function](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/kubelet/cm/devicemanager/manager.go#L439) the DP manager adds the DP's endpoint to a list it maintains. Then the DP manager creates a DP client to interact with the DP (call `list_and_watch` and `allocate`). However, the DP manager also implements the [`RegisterPlugin` function](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/kubelet/cm/devicemanager/manager.go#L319) of the `PluginHandler` interface, which seems to behave the same as `Register` (also kicks off the creation of a device plugin client) and is called by the `PluginManager`. The inline documentation in [the container manager](https://sourcegraph.com/github.com/kubernetes/kubernetes@2112bddae101b35934f1d66288449adf31243033/-/blob/pkg/kubelet/cm/container_manager.go#L106) says this is to enable having a single module for plugin registration. However, I don't see what scenario would cause the [`reconciler` of the `PluginManager`](https://github.com/kubernetes/kubernetes/tree/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/reconciler) to call the DP Manager's `RegisterPlugin`. @thomastaylor312 do you have an understanding of this?

**Comment by bacongobbler** [comment]
From a cursory glance, it looks like the `reconciler` calls `RegisterPlugin` when it discovers that a new plugin is available for registration. It looks like that happens when a new socket file is added with the right timestamp info. This is performed through the `operationExecutor`.

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/pluginmanager/reconciler/reconciler.go#L148-L163

We've gone down this rabbit hole a few times now, each time with a different understanding of the system. I agree that the plugin registration system is not very well documented. The best way we've been able to determine when and where these code paths are called is when we try to reverse engineer the system through some basic tests. Mostly that involves running kubelet on its own and seeing how it responds to certain events, such as when a new plugin is running and the socket file is added to the plugins directory.

Sorry... Your guess is as good as ours.

**Comment by kate-goldenring** [comment]
@bacongobbler thanks for the tip. I tried out some scenarios on my cluster and looking at the kubelet logs and device plugin logs, it seems that while  `Register` is being called by the device plugin, `RegisterPlugin` is never being called by the `reconciler` -- which also means `GetDevicePluginOptions` is never being called. I tried creating a device plugin without registering to see if that would trigger the `reconciler` to call `RegisterPlugin` but that doesn't seem to be the case. It seems like there isn't much use for the `reconciler` for device plugin management, since the device plugin manager hosts its own registration service. 

I have been caught up in trying to imitate the Kubernetes implementation. However, it seems that device plugin support can be added simply by implementing the device plugin manager (without adding the `reconciler` model).

**Comment by kate-goldenring** [comment]
It seems like krustlet doesn't have support for [Kubernetes resource requests](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) by Pods, namely CPU and memory requests and limits. The device plugin framework enables nodes to advertise [extended resources](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/) such as system hardware that pods can later request. In kubernetes, each one of these resources has  manager under the [container manager (cm)](https://github.com/kubernetes/kubernetes/tree/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/cm) directory. Adding device plugin support is the equivalent to adding the device manager. I am not sure if device plugin support can or should be added prior to supporting standard resource requests. Is it on krustlet's roadmap to support memory and cpu resource requests?

**Comment by thomastaylor312** [comment]
Generally speaking, those would have to be provider specific so that krustlet can expose them up to the API server for scheduling decisions. I think in terms of this feature, it would require some extra work, but maybe not as we have worried about. The main work would entail:

1. Creating a new method on the `Provider` trait that allows you to return the resources the node has available (I think k8s keeps track of how much has been allocated, right?)
2. Introducing the plumbing to patch the node with that data

So my question is if the device plugin stuff needs this to work properly. Right now it looks like k8s sets some capacity defaults even if we don't set them, so adding on your own custom ones from the device plugin seems ok and we can add support for normal resource requests down the line

**Comment by kate-goldenring** [comment]
> 1. Creating a new method on the `Provider` trait that allows you to return the resources the node has available (I think k8s keeps track of how much has been allocated, right?)
> 2. Introducing the plumbing to patch the node with that data

@thomastaylor312, like you mentioned, the device manager updates a `Node.status.capacity` and `Node.status.allocatable` fields for each device plugin. I may be missing a deeper understanding of the K8s scheduler, but shouldnt it be able to reference the Node status when making scheduling decisions to know which resources/devices are available? Therefore, is step 1 unnecessary?

**Comment by thomastaylor312** [comment]
Yes, you are correct. That first step was what was required if we wanted to add the normal CPU/memory resource data, but isn't required by this feature. I just got off on a tangent
