### ISSUE TITLE
Fix Clippy Warnings in Krator Derive

### ISSUE THREAD

**Issue by kflansburg** [deislabs/krustlet#599]
#577 introduced some Clippy warnings.

**Comment by kesselborn** [comment]
happy to fix those warnings if you tell me how to recreate them. If I ran clippy within krustlet, krator and krator-derive and had no errors or warnings -- do I need a special config for this?
My setup:

```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.52.1 (9bc8c42bb 2021-05-09)

clippy 0.1.52 (9bc8c42b 2021-05-09)

```

**Comment by kflansburg** [comment]
Thanks Daniel. I saw them when running clippy on the moose example with the admission webhook feature enabled:


```
cd crates/krator
cargo clippy --example moose --features derive-admission-webhook
```
