### ISSUE TITLE
[Question]How to join a krustlet node into self-built k8s cluster rather than KinD,Minikube,GKE etc?

### ISSUE THREAD

**Issue by JesseStutler** [deislabs/krustlet#622]
😊Hi, New to krustlet.A small noob question. I didn't find how to join a krustlet node into self-built k8s cluster(like 3 nodes in normal) in quickstart tutorial `https://github.com/deislabs/krustlet/blob/main/docs/intro/quickstart.md`,not Kind or MicroK8s or minikube or GKE etc. I try to follow the `https://github.com/deislabs/krustlet/blob/main/docs/howto/bootstrapping.md. `But the `bootrstrap.sh` has kubectl command,so it has to run on master node then can create the config.I don't understand why to run command `KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file /path/to/your/bootstrap.conf` on master node..it should run on another node who wants to join the cluster, isn't it? But I have errors to run this command on a node that wants to join the cluster using krustlet. Is there a way like `kubeadm join --token` as kubelet to join the cluster?Please correct me if my saying has wrong and how to build a krustlet node to join a self-built k8s cluster.

**Comment by bacongobbler** [comment]
Hey @JesseStutler!

For the most part, the HOWTO guides provide the same set of instructions:

1. Get a bootstrap config
2. Determine the default network gateway
3. Install and run Krustlet
4. Approve the Certificate

The same set of instructions should be the same on a self-built kubernetes cluster.

As to your specific questions:

> But the bootrstrap.sh has kubectl command,so it has to run on master node

> I don't understand why to run command `KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file /path/to/your/bootstrap.conf` on master node..it should run on another node who wants to join the cluster, isn't it?

You run that command wherever you wish to run a new Node.

I don't see where the documentation describes that you need to run those commands on a master node. `kubectl` does not require you to be on the same node as the master. As long as you have a valid kubeconfig  you should be able to run that anywhere.

Can you please help point where it is required to run `kubectl` on the master node, or clarify where you're getting confused?

> But I have errors to run this command on a node that wants to join the cluster using krustlet.

Would you mind sharing those error messages with us?

Do keep in mind the following [from the bootstrap documentation](https://github.com/deislabs/krustlet/blob/main/docs/howto/bootstrapping.md):

> ## Initialization
> Krustlet follows the same initialization flow as Kubelet (with the exception of automatic renewal of certs that are close to expiry).

> ## Instructions
> In order to join a cluster with the proper permissions, Krustlet requires a valid bootstrap config with a valid bootstrap token. This token can be generated with kubeadm or may already exist depending on your provider. However, in this case, we will be using an easier method for creating a join token. Either way, the examples here should be useful for figuring out how to do it differently depending on your setup.

**Comment by JesseStutler** [comment]
> Can you please help point where it is required to run `kubectl` on the master node, or clarify where you're getting confused? 

Uh....Thanks for your kind sharing. It's my problem....I always use kubectl to run on the master node, never try to use it on worker node....Therfore it gives me illusion that kubectl only can be run on master node😅. After your saying, sure it theoretically can on worker node if it has kubeconfig. I will try to configure it out and if I still have questions I will feed back. Thanks.

**Comment by JesseStutler** [comment]
It does work.Thanks.Close now.

**Comment by ZW007** [comment]
@JesseStutler @bacongobbler  Hello! Can you share a bit more about how you join a krustlet node to the cluster? I followed [this](https://docs.krustlet.dev/howto/bootstrapping/) but do you mean all three steps 1) `./scripts/bootstrap.sh` 2)   `KUBECONFIG=~/.krustlet/config/kubeconfig krustlet-wasi --port 3000 --bootstrap-file /path/to/your/bootstrap.conf` 3) `kubectl certificate approve <hostname>-tls` should all run on a worker node?? But how can kubectl talks to a node that is master (this node is not even in the cluster) So I doing `kubectl` on a new node does not make sense to me, also error `The connection to the server localhost:8080 was refused - did you specify the right host or port?`
