### ISSUE TITLE
Private key file is created with default umask 

### ISSUE THREAD

**Issue by soenkeliebau** [deislabs/krustlet#639]
When using bootstrapping for krustlet, the private key file (and certificate, but not really critical for this) is created without specifying a umask [1].

On most systems this will default to being world readable, which is not ideal for something this critical.

We should look into making this readable for the user running krustlet only.

[1] https://github.com/deislabs/krustlet/blob/e802c9c8b176fc9300d411386e16cc56869887ad/crates/kubelet/src/bootstrapping/mod.rs#L274

**Comment by bacongobbler** [comment]
Using `set_permissions` after creating the file should suffice.

https://github.com/tokio-rs/tokio/blob/c8fc4927482a702c3a89bb8a2f158c430b402e78/tokio/src/fs/file.rs#L476
