### ISSUE TITLE
Add support for multiple runtimes

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#8]
Make sure we support both WASI and waSCC runtimes

**Comment by technosophos** [comment]
After reading lots of Virtual Kubelet, I wanted to sidestep a design hassle I saw there. In VK, to start a project, you basically clone the Virtual Kubelet repo and then start rewriting things to fit your needs. I wanted to make that a little more library-like, so I abstracted all of the backend-specific logic into the `Provider` trait.

Essentially, writing a new Krustlet backend consists entirely of writing a new Provider, with the minimal boilerplate you see in `main.rs`.

The `Kubelet` object only takes one provider, though. There are a few reasons for this (some technical, some not), but the main reason is that it is hard for one top-level system to know enough about all of the providers that it can adequately partition resources. (This is actually one of the same design considerations VK made. It simply doesn't seem right to have multiple providers on the same Kubelet)

Furthermore, my original design was to have WASM-WASI and WASM-WASCC in two different `Providers`. This would have effectively meant that to run both of these, you would need to run two different Krustlets. That is still a design option.

One could argue that one Kubelet should be able to handle both WASM-WASI and WASM-WASCC. (We did it, for example, in the CRI experiment.) If you want to do that, there are a few options:

1. Rewrite `Kubelet` to allow multiple `Provider` backends. This might sound easy, but it actually may be harder than it sounds.
2. Rewrite the `WASM` provider (which currently does waSCC) to do both. This is fine, too, but will be perhaps a little complicated (like the CRI experiment was).
3. Figure out a way to execute regular WASM-WASI modules on waSCC, and just do that. This is the route I was trying to figure out on Krustlet when we switched to the CRI experiment.

**Comment by squillace** [comment]
is wasm3 out of the realm of possibility here? I'd love to be able to drop a kubelet in smaller envrionments.

**Comment by technosophos** [comment]
wasm3, lucet, wasmer.... there are several other runtimes that we currently should at least be open to supporting, even if we can't today

**Comment by thomastaylor312** [comment]
We decided to go the route of having separate kubelets for each type

**Comment by squillace** [comment]
Not a problem. I'd like to support for our current work wasm3, wasmtime, wascc, and consider lucet (though I was of the impression that it was in the process of coalescing with wasmtime...)

**Comment by squillace** [comment]
I leave it in your capable but resource-constrained hands.

**Comment by syrusakbary** [comment]
This is great! Let us know if we can be of any help (I work at Wasmer) 🙂

**Comment by technosophos** [comment]
Thanks! As we settle into a pattern, I think we'll know how to easily add new runtimes.
