### ISSUE TITLE
Create instructions for running Krustlet locally with KinD

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#86]
We should have detailed instructions for configuring and using Krustlet locally with KinD

**Comment by bacongobbler** [comment]
taking this one on

**Comment by bacongobbler** [comment]
This is explained in the documentation tutorial today as part 3 of the tutorial. #125 shift this around under the "Install Krustlet" documentation as a step for running Krustlet locally.

**Comment by thomastaylor312** [comment]
So will #125 technically close this then?

**Comment by bacongobbler** [comment]
Not yet; #125 describes how to boot a Kubernetes cluster with KinD, but it does not fill out the how-to section on booting Krustlet with a KinD cluster.
