### ISSUE TITLE
write a github action to upload compiled assets

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#89]
To prepare for the 0.1.0 release, we should set up a post-merge github action to produce a package containing krustlet, the README and the LICENSE file.

https://help.github.com/en/actions/publishing-packages-with-github-actions/about-packaging-with-github-actions

https://help.github.com/en/packages/publishing-and-managing-packages/about-github-packages

Or we can use my github action and upload the packages to WABS: https://github.com/marketplace/actions/azure-blob-storage-upload

**Comment by thomastaylor312** [comment]
We should also make sure this publishes the crates to crates.io
