### ISSUE TITLE
Use non-hardcoded modules in wascc-provider 

### ISSUE THREAD

**Issue by rylev** [deislabs/krustlet#95]
We are currently using a [hard coded WASM module](https://github.com/deislabs/krustlet/blob/master/crates/wascc-provider/src/lib.rs#L103) in the wascc-provider. This should be replaced with a module store that fetches the module if it's not there and returns the module from a cache.

**Comment by autodidaddict** [comment]
Let me know if you think Gantry would work as a module store here, and if not, if there's something that can be added to Gantry to make it work.
